<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 7 PPI network analysis | TCMDATA: Traditional Chinese Medicine Data Analysis and Visualization</title>
  <meta name="description" content="TCMDATA user guide. Covers installation, core features, and common workflows." />
  <meta name="generator" content="bookdown 0.46 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 7 PPI network analysis | TCMDATA: Traditional Chinese Medicine Data Analysis and Visualization" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="TCMDATA user guide. Covers installation, core features, and common workflows." />
  <meta name="github-repo" content="YuLab-SMU/TCMDATA" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 7 PPI network analysis | TCMDATA: Traditional Chinese Medicine Data Analysis and Visualization" />
  
  <meta name="twitter:description" content="TCMDATA user guide. Covers installation, core features, and common workflows." />
  

<meta name="author" content="Nan He, Guangchuang Yu, Shuangbin Xu Department of Bioinformatics, School of Basic Medical Sciences, Southern Medical University" />


<meta name="date" content="2026-05-28" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="enrichment.html"/>
<link rel="next" href="ml-analysis.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<link href="libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet" />
<script src="libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>
<link href="libs/ggiraphjs-0.9.4/girafe.css" rel="stylesheet" />
<script src="libs/ggiraphjs-0.9.4/girafe.js"></script>
<script src="libs/girafe-binding-0.9.6/girafe.js"></script>
<link href="libs/liberation-sans-0.5.1/css/liberation-sans.css" rel="stylesheet" />
<link href="libs/liberation-serif-0.5.1/css/liberation-serif.css" rel="stylesheet" />
<link href="libs/liberation-mono-0.5.1/css/liberation-mono.css" rel="stylesheet" />


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">TCMDATA User Guide</a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Preface</a>
<ul>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html#installation"><i class="fa fa-check"></i>Installation</a></li>
</ul></li>
<li class="chapter" data-level="1" data-path="load-data.html"><a href="load-data.html"><i class="fa fa-check"></i><b>1</b> Load TCM Data</a>
<ul>
<li class="chapter" data-level="1.1" data-path="load-data.html"><a href="load-data.html#search-by-herb-name"><i class="fa fa-check"></i><b>1.1</b> Search by herb name</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="load-data.html"><a href="load-data.html#using-pinyin-format"><i class="fa fa-check"></i><b>1.1.1</b> Using Pinyin format</a></li>
</ul></li>
<li class="chapter" data-level="1.2" data-path="load-data.html"><a href="load-data.html#search-by-target-gene"><i class="fa fa-check"></i><b>1.2</b> Search by target gene</a></li>
<li class="chapter" data-level="1.3" data-path="load-data.html"><a href="load-data.html#session-information"><i class="fa fa-check"></i><b>1.3</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="pre-analysis.html"><a href="pre-analysis.html"><i class="fa fa-check"></i><b>2</b> Pre-analysis</a>
<ul>
<li class="chapter" data-level="2.1" data-path="pre-analysis.html"><a href="pre-analysis.html#pubmed-literature-mining"><i class="fa fa-check"></i><b>2.1</b> PubMed literature mining</a>
<ul>
<li class="chapter" data-level="2.1.1" data-path="pre-analysis.html"><a href="pre-analysis.html#visualization"><i class="fa fa-check"></i><b>2.1.1</b> Visualization</a></li>
<li class="chapter" data-level="2.1.2" data-path="pre-analysis.html"><a href="pre-analysis.html#exporting-results"><i class="fa fa-check"></i><b>2.1.2</b> Exporting results</a></li>
</ul></li>
<li class="chapter" data-level="2.2" data-path="pre-analysis.html"><a href="pre-analysis.html#herb-ora"><i class="fa fa-check"></i><b>2.2</b> Herb enrichment analysis</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="pre-analysis.html"><a href="pre-analysis.html#example-diabetic-nephropathy"><i class="fa fa-check"></i><b>2.2.1</b> Example: Diabetic Nephropathy</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="pre-analysis.html"><a href="pre-analysis.html#references"><i class="fa fa-check"></i><b>2.3</b> References</a></li>
<li class="chapter" data-level="2.4" data-path="pre-analysis.html"><a href="pre-analysis.html#session-information-1"><i class="fa fa-check"></i><b>2.4</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="molecule-detection.html"><a href="molecule-detection.html"><i class="fa fa-check"></i><b>3</b> Molecule annotation</a>
<ul>
<li class="chapter" data-level="3.1" data-path="molecule-detection.html"><a href="molecule-detection.html#resolving-compound-identifiers"><i class="fa fa-check"></i><b>3.1</b> Resolving compound identifiers</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="molecule-detection.html"><a href="molecule-detection.html#using-resolve_cid"><i class="fa fa-check"></i><b>3.1.1</b> Using <code>resolve_cid()</code></a></li>
<li class="chapter" data-level="3.1.2" data-path="molecule-detection.html"><a href="molecule-detection.html#using-getcid"><i class="fa fa-check"></i><b>3.1.2</b> Using <code>getcid()</code></a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="molecule-detection.html"><a href="molecule-detection.html#retrieving-chemical-properties"><i class="fa fa-check"></i><b>3.2</b> Retrieving chemical properties</a></li>
<li class="chapter" data-level="3.3" data-path="molecule-detection.html"><a href="molecule-detection.html#similarity-searching"><i class="fa fa-check"></i><b>3.3</b> Similarity searching</a></li>
<li class="chapter" data-level="3.4" data-path="molecule-detection.html"><a href="molecule-detection.html#download-molecular-structures-and-format-conversion"><i class="fa fa-check"></i><b>3.4</b> Download molecular structures and format conversion</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="molecule-detection.html"><a href="molecule-detection.html#downloading-ligand-structures-from-pubchem"><i class="fa fa-check"></i><b>3.4.1</b> Downloading ligand structures from PubChem</a></li>
<li class="chapter" data-level="3.4.2" data-path="molecule-detection.html"><a href="molecule-detection.html#downloading-receptor-structures-from-the-rcsb-pdb"><i class="fa fa-check"></i><b>3.4.2</b> Downloading receptor structures from the RCSB PDB</a></li>
<li class="chapter" data-level="3.4.3" data-path="molecule-detection.html"><a href="molecule-detection.html#converting-structure-file-formats"><i class="fa fa-check"></i><b>3.4.3</b> Converting structure file formats</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="molecule-detection.html"><a href="molecule-detection.html#references-1"><i class="fa fa-check"></i><b>3.5</b> References</a></li>
<li class="chapter" data-level="3.6" data-path="molecule-detection.html"><a href="molecule-detection.html#session-information-2"><i class="fa fa-check"></i><b>3.6</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="target-retrieval.html"><a href="target-retrieval.html"><i class="fa fa-check"></i><b>4</b> Target retrieval and DEG analysis</a>
<ul>
<li class="chapter" data-level="4.1" data-path="target-retrieval.html"><a href="target-retrieval.html#disease-target-tcmdata"><i class="fa fa-check"></i><b>4.1</b> Programmatic disease target retrieval with TCMDATA</a>
<ul>
<li class="chapter" data-level="4.1.1" data-path="target-retrieval.html"><a href="target-retrieval.html#search_disease-disease-genes"><i class="fa fa-check"></i><b>4.1.1</b> <code>search_disease()</code>: disease → genes</a></li>
<li class="chapter" data-level="4.1.2" data-path="target-retrieval.html"><a href="target-retrieval.html#search_gene_disease-gene-diseases"><i class="fa fa-check"></i><b>4.1.2</b> <code>search_gene_disease()</code>: gene → diseases</a></li>
<li class="chapter" data-level="4.1.3" data-path="target-retrieval.html"><a href="target-retrieval.html#open-targets-api-disease-scored-targets"><i class="fa fa-check"></i><b>4.1.3</b> Open Targets API: disease → scored targets</a></li>
</ul></li>
<li class="chapter" data-level="4.2" data-path="target-retrieval.html"><a href="target-retrieval.html#disease-db"><i class="fa fa-check"></i><b>4.2</b> Disease target databases</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="target-retrieval.html"><a href="target-retrieval.html#genecards"><i class="fa fa-check"></i><b>4.2.1</b> GeneCards</a></li>
<li class="chapter" data-level="4.2.2" data-path="target-retrieval.html"><a href="target-retrieval.html#open-targets-platform"><i class="fa fa-check"></i><b>4.2.2</b> Open Targets Platform</a></li>
<li class="chapter" data-level="4.2.3" data-path="target-retrieval.html"><a href="target-retrieval.html#ctd-comparative-toxicogenomics-database"><i class="fa fa-check"></i><b>4.2.3</b> CTD (Comparative Toxicogenomics Database)</a></li>
<li class="chapter" data-level="4.2.4" data-path="target-retrieval.html"><a href="target-retrieval.html#other-databases"><i class="fa fa-check"></i><b>4.2.4</b> Other databases</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="target-retrieval.html"><a href="target-retrieval.html#compound-target"><i class="fa fa-check"></i><b>4.3</b> Compound target prediction</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="target-retrieval.html"><a href="target-retrieval.html#compound-target-swisstarget"><i class="fa fa-check"></i><b>4.3.1</b> SwissTargetPrediction</a></li>
<li class="chapter" data-level="4.3.2" data-path="target-retrieval.html"><a href="target-retrieval.html#similarity-ensemble-approach-sea"><i class="fa fa-check"></i><b>4.3.2</b> Similarity Ensemble Approach (SEA)</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="target-retrieval.html"><a href="target-retrieval.html#volcano"><i class="fa fa-check"></i><b>4.4</b> DEG visualization</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="target-retrieval.html"><a href="target-retrieval.html#load-and-inspect-data"><i class="fa fa-check"></i><b>4.4.1</b> Load and inspect data</a></li>
<li class="chapter" data-level="4.4.2" data-path="target-retrieval.html"><a href="target-retrieval.html#volcano-plot-with-ivolcano"><i class="fa fa-check"></i><b>4.4.2</b> Volcano plot with <code>ivolcano</code></a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="target-retrieval.html"><a href="target-retrieval.html#intersection"><i class="fa fa-check"></i><b>4.5</b> Intersection analysis</a>
<ul>
<li class="chapter" data-level="4.5.1" data-path="target-retrieval.html"><a href="target-retrieval.html#prepare-gene-sets"><i class="fa fa-check"></i><b>4.5.1</b> Prepare gene sets</a></li>
<li class="chapter" data-level="4.5.2" data-path="target-retrieval.html"><a href="target-retrieval.html#venn-diagram"><i class="fa fa-check"></i><b>4.5.2</b> Venn diagram</a></li>
<li class="chapter" data-level="4.5.3" data-path="target-retrieval.html"><a href="target-retrieval.html#upset-plot"><i class="fa fa-check"></i><b>4.5.3</b> UpSet plot</a></li>
<li class="chapter" data-level="4.5.4" data-path="target-retrieval.html"><a href="target-retrieval.html#extract-intersection-results"><i class="fa fa-check"></i><b>4.5.4</b> Extract intersection results</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="target-retrieval.html"><a href="target-retrieval.html#ppi-weighted-target-ranking"><i class="fa fa-check"></i><b>4.6</b> PPI-weighted target ranking</a>
<ul>
<li class="chapter" data-level="4.6.1" data-path="target-retrieval.html"><a href="target-retrieval.html#example-lingzhi-targets-against-dn-disease-module"><i class="fa fa-check"></i><b>4.6.1</b> Example: Lingzhi targets against DN disease module</a></li>
</ul></li>
<li class="chapter" data-level="4.7" data-path="target-retrieval.html"><a href="target-retrieval.html#references-2"><i class="fa fa-check"></i><b>4.7</b> References</a></li>
<li class="chapter" data-level="4.8" data-path="target-retrieval.html"><a href="target-retrieval.html#session-information-3"><i class="fa fa-check"></i><b>4.8</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="network-construction.html"><a href="network-construction.html"><i class="fa fa-check"></i><b>5</b> TCM network construction</a>
<ul>
<li class="chapter" data-level="5.1" data-path="network-construction.html"><a href="network-construction.html#preparing-the-data"><i class="fa fa-check"></i><b>5.1</b> Preparing the data</a></li>
<li class="chapter" data-level="5.2" data-path="network-construction.html"><a href="network-construction.html#sankey-diagram-visualization"><i class="fa fa-check"></i><b>5.2</b> Sankey diagram visualization</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="network-construction.html"><a href="network-construction.html#basic-usage"><i class="fa fa-check"></i><b>5.2.1</b> Basic usage</a></li>
<li class="chapter" data-level="5.2.2" data-path="network-construction.html"><a href="network-construction.html#customizing-colors-and-appearance"><i class="fa fa-check"></i><b>5.2.2</b> Customizing colors and appearance</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="network-construction.html"><a href="network-construction.html#network-graph-with-ggtangle"><i class="fa fa-check"></i><b>5.3</b> Network graph with <code>ggtangle</code></a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="network-construction.html"><a href="network-construction.html#building-the-graph"><i class="fa fa-check"></i><b>5.3.1</b> Building the graph</a></li>
<li class="chapter" data-level="5.3.2" data-path="network-construction.html"><a href="network-construction.html#basic-network-visualization"><i class="fa fa-check"></i><b>5.3.2</b> Basic network visualization</a></li>
<li class="chapter" data-level="5.3.3" data-path="network-construction.html"><a href="network-construction.html#adding-node-labels"><i class="fa fa-check"></i><b>5.3.3</b> Adding node labels</a></li>
<li class="chapter" data-level="5.3.4" data-path="network-construction.html"><a href="network-construction.html#alternative-layouts"><i class="fa fa-check"></i><b>5.3.4</b> Alternative layouts</a></li>
<li class="chapter" data-level="5.3.5" data-path="network-construction.html"><a href="network-construction.html#enriching-the-network-with-external-data"><i class="fa fa-check"></i><b>5.3.5</b> Enriching the network with external data</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="network-construction.html"><a href="network-construction.html#references-3"><i class="fa fa-check"></i><b>5.4</b> References</a></li>
<li class="chapter" data-level="5.5" data-path="network-construction.html"><a href="network-construction.html#session-information-4"><i class="fa fa-check"></i><b>5.5</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="enrichment.html"><a href="enrichment.html"><i class="fa fa-check"></i><b>6</b> Enrichment analysis</a>
<ul>
<li class="chapter" data-level="6.1" data-path="enrichment.html"><a href="enrichment.html#over-representation-analysis-ora"><i class="fa fa-check"></i><b>6.1</b> Over Representation Analysis (ORA)</a>
<ul>
<li class="chapter" data-level="6.1.1" data-path="enrichment.html"><a href="enrichment.html#kegg-enrichment-analysis"><i class="fa fa-check"></i><b>6.1.1</b> KEGG enrichment analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.2" data-path="enrichment.html"><a href="enrichment.html#go-enrichment-analysis"><i class="fa fa-check"></i><b>6.2</b> GO enrichment analysis</a></li>
<li class="chapter" data-level="6.3" data-path="enrichment.html"><a href="enrichment.html#advanced-visualization"><i class="fa fa-check"></i><b>6.3</b> Advanced visualization</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="enrichment.html"><a href="enrichment.html#lollipop-plot"><i class="fa fa-check"></i><b>6.3.1</b> Lollipop plot</a></li>
<li class="chapter" data-level="6.3.2" data-path="enrichment.html"><a href="enrichment.html#dot-sankey-plot"><i class="fa fa-check"></i><b>6.3.2</b> Dot-sankey plot</a></li>
<li class="chapter" data-level="6.3.3" data-path="enrichment.html"><a href="enrichment.html#go-bar-plot"><i class="fa fa-check"></i><b>6.3.3</b> GO bar plot</a></li>
<li class="chapter" data-level="6.3.4" data-path="enrichment.html"><a href="enrichment.html#go-circle-plot"><i class="fa fa-check"></i><b>6.3.4</b> GO circle plot</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="enrichment.html"><a href="enrichment.html#gene-set-enrichment-analysis-gsea"><i class="fa fa-check"></i><b>6.4</b> Gene Set Enrichment Analysis (GSEA)</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="enrichment.html"><a href="enrichment.html#prepare-ranked-gene-list"><i class="fa fa-check"></i><b>6.4.1</b> Prepare ranked gene list</a></li>
<li class="chapter" data-level="6.4.2" data-path="enrichment.html"><a href="enrichment.html#kegg-gsea-analysis"><i class="fa fa-check"></i><b>6.4.2</b> KEGG GSEA analysis</a></li>
<li class="chapter" data-level="6.4.3" data-path="enrichment.html"><a href="enrichment.html#go-gsea-analysis"><i class="fa fa-check"></i><b>6.4.3</b> GO GSEA analysis</a></li>
</ul></li>
<li class="chapter" data-level="6.5" data-path="enrichment.html"><a href="enrichment.html#session-information-5"><i class="fa fa-check"></i><b>6.5</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="7" data-path="ppi-analysis.html"><a href="ppi-analysis.html"><i class="fa fa-check"></i><b>7</b> PPI network analysis</a>
<ul>
<li class="chapter" data-level="7.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#retrieving-ppi-data-from-string"><i class="fa fa-check"></i><b>7.1</b> Retrieving PPI data from STRING</a></li>
<li class="chapter" data-level="7.2" data-path="ppi-analysis.html"><a href="ppi-analysis.html#network-filtering"><i class="fa fa-check"></i><b>7.2</b> Network filtering</a></li>
<li class="chapter" data-level="7.3" data-path="ppi-analysis.html"><a href="ppi-analysis.html#ppi-target-set-proximity"><i class="fa fa-check"></i><b>7.3</b> Target-set proximity to a disease PPI module</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#example-evaluating-lingzhi-target-set-against-dn"><i class="fa fa-check"></i><b>7.3.1</b> Example: evaluating Lingzhi target set against DN</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="ppi-analysis.html"><a href="ppi-analysis.html#topology"><i class="fa fa-check"></i><b>7.4</b> Topological metrics</a>
<ul>
<li class="chapter" data-level="7.4.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#integrated-ranking"><i class="fa fa-check"></i><b>7.4.1</b> Integrated ranking</a></li>
<li class="chapter" data-level="7.4.2" data-path="ppi-analysis.html"><a href="ppi-analysis.html#radar-plot-of-topological-metrics"><i class="fa fa-check"></i><b>7.4.2</b> Radar plot of topological metrics</a></li>
<li class="chapter" data-level="7.4.3" data-path="ppi-analysis.html"><a href="ppi-analysis.html#heatmap-of-topological-metrics"><i class="fa fa-check"></i><b>7.4.3</b> Heatmap of topological metrics</a></li>
</ul></li>
<li class="chapter" data-level="7.5" data-path="ppi-analysis.html"><a href="ppi-analysis.html#clustering"><i class="fa fa-check"></i><b>7.5</b> Community detection</a>
<ul>
<li class="chapter" data-level="7.5.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#louvain-modularity-optimization"><i class="fa fa-check"></i><b>7.5.1</b> Louvain modularity optimization</a></li>
<li class="chapter" data-level="7.5.2" data-path="ppi-analysis.html"><a href="ppi-analysis.html#mcode-molecular-complex-detection"><i class="fa fa-check"></i><b>7.5.2</b> MCODE (Molecular Complex Detection)</a></li>
<li class="chapter" data-level="7.5.3" data-path="ppi-analysis.html"><a href="ppi-analysis.html#mcl-markov-clustering"><i class="fa fa-check"></i><b>7.5.3</b> MCL (Markov Clustering)</a></li>
<li class="chapter" data-level="7.5.4" data-path="ppi-analysis.html"><a href="ppi-analysis.html#fast-greedy-modularity-optimization"><i class="fa fa-check"></i><b>7.5.4</b> Fast greedy modularity optimization</a></li>
</ul></li>
<li class="chapter" data-level="7.6" data-path="ppi-analysis.html"><a href="ppi-analysis.html#robustness"><i class="fa fa-check"></i><b>7.6</b> PPI network robustness analysis</a>
<ul>
<li class="chapter" data-level="7.6.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#algorithm-overview"><i class="fa fa-check"></i><b>7.6.1</b> Algorithm overview</a></li>
<li class="chapter" data-level="7.6.2" data-path="ppi-analysis.html"><a href="ppi-analysis.html#example-knocking-out-il6"><i class="fa fa-check"></i><b>7.6.2</b> Example: knocking out IL6</a></li>
<li class="chapter" data-level="7.6.3" data-path="ppi-analysis.html"><a href="ppi-analysis.html#visualization-before-vs.-after-knockout"><i class="fa fa-check"></i><b>7.6.3</b> Visualization: before vs. after knockout</a></li>
</ul></li>
<li class="chapter" data-level="7.7" data-path="ppi-analysis.html"><a href="ppi-analysis.html#ppi-vis"><i class="fa fa-check"></i><b>7.7</b> PPI network visualization</a>
<ul>
<li class="chapter" data-level="7.7.1" data-path="ppi-analysis.html"><a href="ppi-analysis.html#basic-network-with-topological-mapping"><i class="fa fa-check"></i><b>7.7.1</b> Basic network with topological mapping</a></li>
<li class="chapter" data-level="7.7.2" data-path="ppi-analysis.html"><a href="ppi-analysis.html#community-colored-network"><i class="fa fa-check"></i><b>7.7.2</b> Community-colored network</a></li>
<li class="chapter" data-level="7.7.3" data-path="ppi-analysis.html"><a href="ppi-analysis.html#hub-centric-star-layout"><i class="fa fa-check"></i><b>7.7.3</b> Hub-centric star layout</a></li>
<li class="chapter" data-level="7.7.4" data-path="ppi-analysis.html"><a href="ppi-analysis.html#layout-algorithm-comparison"><i class="fa fa-check"></i><b>7.7.4</b> Layout algorithm comparison</a></li>
</ul></li>
<li class="chapter" data-level="7.8" data-path="ppi-analysis.html"><a href="ppi-analysis.html#references-4"><i class="fa fa-check"></i><b>7.8</b> References</a></li>
<li class="chapter" data-level="7.9" data-path="ppi-analysis.html"><a href="ppi-analysis.html#session-information-6"><i class="fa fa-check"></i><b>7.9</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="ml-analysis.html"><a href="ml-analysis.html"><i class="fa fa-check"></i><b>8</b> Machine learning–based key target screening</a>
<ul>
<li class="chapter" data-level="8.1" data-path="ml-analysis.html"><a href="ml-analysis.html#introduction"><i class="fa fa-check"></i><b>8.1</b> Introduction</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-data"><i class="fa fa-check"></i><b>8.1.1</b> Example dataset</a></li>
<li class="chapter" data-level="8.1.2" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-prepare"><i class="fa fa-check"></i><b>8.1.2</b> Data preparation</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-mode-a"><i class="fa fa-check"></i><b>8.2</b> Mode A: full cross-validation</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-lasso"><i class="fa fa-check"></i><b>8.2.1</b> LASSO regression</a></li>
<li class="chapter" data-level="8.2.2" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-rf"><i class="fa fa-check"></i><b>8.2.2</b> Random Forest and Boruta</a></li>
<li class="chapter" data-level="8.2.3" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-svm-rfe"><i class="fa fa-check"></i><b>8.2.3</b> SVM-RFE</a></li>
<li class="chapter" data-level="8.2.4" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-xgboost"><i class="fa fa-check"></i><b>8.2.4</b> XGBoost</a></li>
<li class="chapter" data-level="8.2.5" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-consensus"><i class="fa fa-check"></i><b>8.2.5</b> Consensus analysis</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-mode-b"><i class="fa fa-check"></i><b>8.3</b> Mode B: internal train/test split</a></li>
<li class="chapter" data-level="8.4" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-mode-c"><i class="fa fa-check"></i><b>8.4</b> Mode C: external validation</a></li>
<li class="chapter" data-level="8.5" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-select"><i class="fa fa-check"></i><b>8.5</b> Post-hoc feature trimming</a></li>
<li class="chapter" data-level="8.6" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-manual-list"><i class="fa fa-check"></i><b>8.6</b> Assembling models manually</a></li>
<li class="chapter" data-level="8.7" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-gene-diag"><i class="fa fa-check"></i><b>8.7</b> Single-gene diagnostic analysis</a>
<ul>
<li class="chapter" data-level="8.7.1" data-path="ml-analysis.html"><a href="ml-analysis.html#auc-summary-table"><i class="fa fa-check"></i><b>8.7.1</b> AUC summary table</a></li>
<li class="chapter" data-level="8.7.2" data-path="ml-analysis.html"><a href="ml-analysis.html#single-gene-roc-curves"><i class="fa fa-check"></i><b>8.7.2</b> Single-gene ROC curves</a></li>
<li class="chapter" data-level="8.7.3" data-path="ml-analysis.html"><a href="ml-analysis.html#two-group-expression-boxplot"><i class="fa fa-check"></i><b>8.7.3</b> Two-group expression boxplot</a></li>
</ul></li>
<li class="chapter" data-level="8.8" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-summary"><i class="fa fa-check"></i><b>8.8</b> Summary</a></li>
<li class="chapter" data-level="8.9" data-path="ml-analysis.html"><a href="ml-analysis.html#references-5"><i class="fa fa-check"></i><b>8.9</b> References</a></li>
<li class="chapter" data-level="8.10" data-path="ml-analysis.html"><a href="ml-analysis.html#ml-session-info"><i class="fa fa-check"></i><b>8.10</b> Session Information</a></li>
</ul></li>
<li class="chapter" data-level="9" data-path="ai-module.html"><a href="ai-module.html"><i class="fa fa-check"></i><b>9</b> AI Module</a>
<ul>
<li class="chapter" data-level="9.1" data-path="ai-module.html"><a href="ai-module.html#prerequisites"><i class="fa fa-check"></i><b>9.1</b> Prerequisites</a></li>
<li class="chapter" data-level="9.2" data-path="ai-module.html"><a href="ai-module.html#interpretation-layer"><i class="fa fa-check"></i><b>9.2</b> Interpretation layer</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="ai-module.html"><a href="ai-module.html#free-text-interpretation"><i class="fa fa-check"></i><b>9.2.1</b> Free-text interpretation</a></li>
<li class="chapter" data-level="9.2.2" data-path="ai-module.html"><a href="ai-module.html#interpreting-enrichment-objects"><i class="fa fa-check"></i><b>9.2.2</b> Interpreting enrichment objects</a></li>
<li class="chapter" data-level="9.2.3" data-path="ai-module.html"><a href="ai-module.html#interpreting-ppi-objects"><i class="fa fa-check"></i><b>9.2.3</b> Interpreting PPI objects</a></li>
<li class="chapter" data-level="9.2.4" data-path="ai-module.html"><a href="ai-module.html#drafting-result-paragraphs"><i class="fa fa-check"></i><b>9.2.4</b> Drafting result paragraphs</a></li>
<li class="chapter" data-level="9.2.5" data-path="ai-module.html"><a href="ai-module.html#custom-structured-output"><i class="fa fa-check"></i><b>9.2.5</b> Custom structured output</a></li>
</ul></li>
<li class="chapter" data-level="9.3" data-path="ai-module.html"><a href="ai-module.html#agent-layer"><i class="fa fa-check"></i><b>9.3</b> Agent layer</a>
<ul>
<li class="chapter" data-level="9.3.1" data-path="ai-module.html"><a href="ai-module.html#one-shot-task-tcm_agent"><i class="fa fa-check"></i><b>9.3.1</b> One-shot task: <code>tcm_agent()</code></a></li>
<li class="chapter" data-level="9.3.2" data-path="ai-module.html"><a href="ai-module.html#interactive-session-tcm_chat"><i class="fa fa-check"></i><b>9.3.2</b> Interactive session: <code>tcm_chat()</code></a></li>
<li class="chapter" data-level="9.3.3" data-path="ai-module.html"><a href="ai-module.html#programmatic-agent-create_tcm_task_agent"><i class="fa fa-check"></i><b>9.3.3</b> Programmatic agent: <code>create_tcm_task_agent()</code></a></li>
<li class="chapter" data-level="9.3.4" data-path="ai-module.html"><a href="ai-module.html#artifact-management"><i class="fa fa-check"></i><b>9.3.4</b> Artifact management</a></li>
</ul></li>
<li class="chapter" data-level="9.4" data-path="ai-module.html"><a href="ai-module.html#skill-layer"><i class="fa fa-check"></i><b>9.4</b> Skill layer</a>
<ul>
<li class="chapter" data-level="9.4.1" data-path="ai-module.html"><a href="ai-module.html#built-in-skills"><i class="fa fa-check"></i><b>9.4.1</b> Built-in skills</a></li>
<li class="chapter" data-level="9.4.2" data-path="ai-module.html"><a href="ai-module.html#how-skills-work"><i class="fa fa-check"></i><b>9.4.2</b> How skills work</a></li>
<li class="chapter" data-level="9.4.3" data-path="ai-module.html"><a href="ai-module.html#creating-custom-skills"><i class="fa fa-check"></i><b>9.4.3</b> Creating custom skills</a></li>
<li class="chapter" data-level="9.4.4" data-path="ai-module.html"><a href="ai-module.html#managing-skills"><i class="fa fa-check"></i><b>9.4.4</b> Managing skills</a></li>
</ul></li>
<li class="chapter" data-level="9.5" data-path="ai-module.html"><a href="ai-module.html#session-information-7"><i class="fa fa-check"></i><b>9.5</b> Session information</a></li>
</ul></li>
<li class="chapter" data-level="10" data-path="other-resources.html"><a href="other-resources.html"><i class="fa fa-check"></i><b>10</b> Other resources</a>
<ul>
<li class="chapter" data-level="10.1" data-path="other-resources.html"><a href="other-resources.html#additional-databases"><i class="fa fa-check"></i><b>10.1</b> Additional databases</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="other-resources.html"><a href="other-resources.html#tfgene-interactions-dorothea"><i class="fa fa-check"></i><b>10.1.1</b> TF–gene interactions (DoRothEA)</a></li>
<li class="chapter" data-level="10.1.2" data-path="other-resources.html"><a href="other-resources.html#gut-microbiotahost-interactions-gutmgene"><i class="fa fa-check"></i><b>10.1.2</b> Gut microbiota–host interactions (GutMGene)</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="other-resources.html"><a href="other-resources.html#additional-visualization"><i class="fa fa-check"></i><b>10.2</b> Additional visualization</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="other-resources.html"><a href="other-resources.html#heatmap-for-molecular-docking-results"><i class="fa fa-check"></i><b>10.2.1</b> Heatmap for molecular docking results</a></li>
<li class="chapter" data-level="10.2.2" data-path="other-resources.html"><a href="other-resources.html#to-be-continued"><i class="fa fa-check"></i><b>10.2.2</b> To be continued</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="other-resources.html"><a href="other-resources.html#references-6"><i class="fa fa-check"></i><b>10.3</b> References</a></li>
<li class="chapter" data-level="10.4" data-path="other-resources.html"><a href="other-resources.html#session-information-8"><i class="fa fa-check"></i><b>10.4</b> Session information</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/YuLab-SMU/TCMDATA" target="_blank">GitHub</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">TCMDATA: Traditional Chinese Medicine Data Analysis and Visualization</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="ppi-analysis" class="section level1 hasAnchor" number="7">
<h1><span class="header-section-number">Chapter 7</span> PPI network analysis<a href="ppi-analysis.html#ppi-analysis" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>Protein–protein interaction (PPI) networks are essential for deciphering the functional relationships among disease-related targets. <code>TCMDATA</code> provides a comprehensive PPI analysis pipeline that integrates data retrieval from STRING, network filtering, topological metric computation, community detection, and publication-ready visualization.</p>
<hr />
<div id="retrieving-ppi-data-from-string" class="section level2 hasAnchor" number="7.1">
<h2><span class="header-section-number">7.1</span> Retrieving PPI data from STRING<a href="ppi-analysis.html#retrieving-ppi-data-from-string" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p><code>TCMDATA</code> provides <code>get_ppi()</code> function, a thin wrapper around <code>clusterProfiler::getPPI()</code>, to retrieve Protein-Protein Interaction (PPI) information from the STRING database and return an <code>igraph</code> object containing known and predicted protein–protein interactions, with edge weights representing combined confidence scores (range 0–1).</p>
<p>User can retrieve PPI network for a given set of genes using <code>get_ppi()</code> by specifying the taxonomic ID (e.g., <code>9606</code> for human, <code>10090</code> for mouse):</p>
<div class="sourceCode" id="cb134"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb134-1"><a href="ppi-analysis.html#cb134-1" tabindex="-1"></a><span class="fu">library</span>(TCMDATA)</span>
<span id="cb134-2"><a href="ppi-analysis.html#cb134-2" tabindex="-1"></a></span>
<span id="cb134-3"><a href="ppi-analysis.html#cb134-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;dn_gcds&quot;</span>)</span>
<span id="cb134-4"><a href="ppi-analysis.html#cb134-4" tabindex="-1"></a></span>
<span id="cb134-5"><a href="ppi-analysis.html#cb134-5" tabindex="-1"></a>ppi <span class="ot">&lt;-</span> <span class="fu">get_ppi</span>(dn_gcds[<span class="dv">1</span><span class="sc">:</span><span class="dv">50</span>], <span class="at">taxID =</span> <span class="dv">9606</span>)</span></code></pre></div>
<p>In this example, we use a demo ppi from Diabetic Nephropathy (DN) gene set to illustrate the workflow:</p>
<div class="sourceCode" id="cb135"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb135-1"><a href="ppi-analysis.html#cb135-1" tabindex="-1"></a><span class="fu">library</span>(TCMDATA)</span>
<span id="cb135-2"><a href="ppi-analysis.html#cb135-2" tabindex="-1"></a></span>
<span id="cb135-3"><a href="ppi-analysis.html#cb135-3" tabindex="-1"></a><span class="fu">data</span>(<span class="st">&quot;demo_ppi&quot;</span>)</span>
<span id="cb135-4"><a href="ppi-analysis.html#cb135-4" tabindex="-1"></a>ppi <span class="ot">&lt;-</span> demo_ppi</span>
<span id="cb135-5"><a href="ppi-analysis.html#cb135-5" tabindex="-1"></a>ppi</span></code></pre></div>
<pre><code>#&gt; IGRAPH 3f74811 UN-- 58 611 -- 
#&gt; + attr: name (v/c), score (e/n)
#&gt; + edges from 3f74811 (vertex names):
#&gt;  [1] SLC2A3  --SERPINE1 SLC2A3  --MYC      RELB    --CCL3     RELB    --ATF3    
#&gt;  [5] RELB    --CXCR4    RELB    --SELE     RELB    --KLF6     RELB    --CXCL1   
#&gt;  [9] RELB    --CEBPB    RELB    --VCAM1    RELB    --CCL20    RELB    --FOS     
#&gt; [13] RELB    --PTGS2    RELB    --IL1RN    RELB    --MYC      RELB    --CCL2    
#&gt; [17] RELB    --JUN      RELB    --CXCL8    RELB    --ICAM1    RELB    --TRAF1   
#&gt; [21] RELB    --IL6      RELB    --IL1B     RELB    --BIRC3    RELB    --NFKB2   
#&gt; [25] SERPINE1--CCL4     SERPINE1--MCL1     SERPINE1--S100A8   SERPINE1--IL1RN   
#&gt; [29] SERPINE1--EGR1     SERPINE1--FOS      SERPINE1--IL18     SERPINE1--CCL3    
#&gt; + ... omitted several edges</code></pre>
<p>The returned <code>igraph</code> object contains a <code>score</code> edge attribute representing STRING combined confidence scores, where higher values indicate stronger evidence for the interaction.</p>
<hr />
</div>
<div id="network-filtering" class="section level2 hasAnchor" number="7.2">
<h2><span class="header-section-number">7.2</span> Network filtering<a href="ppi-analysis.html#network-filtering" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Raw PPI networks often contain low-confidence edges that introduce noise. <code>ppi_subset()</code> provides a two-stage filter:</p>
<ol style="list-style-type: decimal">
<li><strong>Edge score cutoff</strong> — removes edges below a confidence threshold.</li>
<li><strong>Top-<em>n</em> degree filter</strong> — retains only the <em>n</em> most connected nodes.</li>
</ol>
<p>In this case, we keep edges with a STRING score ≥ 0.7 and then retain the top 100 nodes by degree:</p>
<div class="sourceCode" id="cb137"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb137-1"><a href="ppi-analysis.html#cb137-1" tabindex="-1"></a>ppi_filtered <span class="ot">&lt;-</span> <span class="fu">ppi_subset</span>(ppi, <span class="at">score_cutoff =</span> <span class="fl">0.7</span>, <span class="at">n =</span> <span class="dv">100</span>)</span>
<span id="cb137-2"><a href="ppi-analysis.html#cb137-2" tabindex="-1"></a></span>
<span id="cb137-3"><a href="ppi-analysis.html#cb137-3" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Before filtering:&quot;</span>, <span class="fu">vcount</span>(ppi), <span class="st">&quot;nodes,&quot;</span>, <span class="fu">ecount</span>(ppi), <span class="st">&quot;edges</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; Before filtering: 58 nodes, 611 edges</code></pre>
<div class="sourceCode" id="cb139"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb139-1"><a href="ppi-analysis.html#cb139-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;After  filtering:&quot;</span>, <span class="fu">vcount</span>(ppi_filtered), <span class="st">&quot;nodes,&quot;</span>, <span class="fu">ecount</span>(ppi_filtered), <span class="st">&quot;edges</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; After  filtering: 49 nodes, 196 edges</code></pre>
<table>
<thead>
<tr class="header">
<th>Parameter</th>
<th>Description</th>
<th>Default</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>score_cutoff</code></td>
<td>Minimum edge confidence to retain</td>
<td>0.7</td>
</tr>
<tr class="even">
<td><code>n</code></td>
<td>Top-<em>n</em> nodes by degree (NULL = all)</td>
<td>NULL</td>
</tr>
<tr class="odd">
<td><code>rm_isolates</code></td>
<td>Remove nodes with degree 0 after filtering</td>
<td>TRUE</td>
</tr>
</tbody>
</table>
<hr />
</div>
<div id="ppi-target-set-proximity" class="section level2 hasAnchor" number="7.3">
<h2><span class="header-section-number">7.3</span> Target-set proximity to a disease PPI module<a href="ppi-analysis.html#ppi-target-set-proximity" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>In addition to constructing a PPI network for a selected gene list, an important network pharmacology question is whether a <strong>target set</strong> is globally close to a disease module in the human PPI background. This is especially useful for comparing:</p>
<ol style="list-style-type: decimal">
<li>Different herbs or formulas against the same disease.</li>
<li>Formula designs before and after optimization.</li>
<li>Candidate herb combinations, compound combinations, or target sets.</li>
</ol>
<p><code>TCMDATA</code> provides <code>evaluate_tcm_target_sets_by_ppi()</code> for this set-level analysis. Unlike <code>rank_tcm_targets_by_ppi()</code>, which ranks individual herb targets, this function evaluates the relationship between a target set <code>H</code> and a weighted disease module <code>D</code>.</p>
<p>The function reports five complementary network metrics:</p>
<table>
<colgroup>
<col width="47%" />
<col width="52%" />
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Meaning</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>overlap_n</code></td>
<td>Number of direct shared targets between <code>H</code> and <code>D</code></td>
</tr>
<tr class="even">
<td><code>directlink_edges</code></td>
<td>Number of one-step PPI links from non-overlap targets in <code>H</code> to disease targets in <code>D</code></td>
</tr>
<tr class="odd">
<td><code>jaccard</code></td>
<td>Direct set similarity, <code>|H ∩ D| / |H ∪ D|</code></td>
</tr>
<tr class="even">
<td><code>weighted_proximity</code></td>
<td>Disease-weighted PPI proximity between <code>H</code> and <code>D</code></td>
</tr>
<tr class="odd">
<td><code>z_proximity</code></td>
<td>Degree-matched random-background Z-score for the observed proximity</td>
</tr>
</tbody>
</table>
<p>The weighted proximity is calculated from shortest-path distances on the PPI network:</p>
<pre class="text"><code>proximity(h, D) =
  weighted.mean(1 / (1 + shortest_path_distance(h, d)),
                disease_weight[d])

weighted_proximity(H, D) =
  weighted.mean(proximity(h, D), target_weight[h])</code></pre>
<p>To control for the fact that high-degree proteins are naturally closer to many network modules, the function samples random target sets with matched degree bins and calculates:</p>
<pre class="text"><code>z_proximity = (observed_proximity - mean(random_proximity)) /
              sd(random_proximity)</code></pre>
<p>A positive <code>z_proximity</code> means that the target set is closer to the disease module than expected from same-degree random target sets.</p>
<div id="example-evaluating-lingzhi-target-set-against-dn" class="section level3 hasAnchor" number="7.3.1">
<h3><span class="header-section-number">7.3.1</span> Example: evaluating Lingzhi target set against DN<a href="ppi-analysis.html#example-evaluating-lingzhi-target-set-against-dn" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For the DN case study, we can combine GeneCards and Open Targets scores into a weighted disease module, then evaluate whether the Lingzhi target set is close to this DN module in the built-in human STRING PPI background:</p>
<div class="sourceCode" id="cb143"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb143-1"><a href="ppi-analysis.html#cb143-1" tabindex="-1"></a><span class="fu">library</span>(TCMDATA)</span>
<span id="cb143-2"><a href="ppi-analysis.html#cb143-2" tabindex="-1"></a></span>
<span id="cb143-3"><a href="ppi-analysis.html#cb143-3" tabindex="-1"></a><span class="do">## weighted DN disease module</span></span>
<span id="cb143-4"><a href="ppi-analysis.html#cb143-4" tabindex="-1"></a><span class="fu">data</span>(dn_gcds_tbl)</span>
<span id="cb143-5"><a href="ppi-analysis.html#cb143-5" tabindex="-1"></a><span class="fu">data</span>(dn_otp_tbl)</span>
<span id="cb143-6"><a href="ppi-analysis.html#cb143-6" tabindex="-1"></a></span>
<span id="cb143-7"><a href="ppi-analysis.html#cb143-7" tabindex="-1"></a>disease_w <span class="ot">&lt;-</span> <span class="fu">prepare_disease_weights</span>(</span>
<span id="cb143-8"><a href="ppi-analysis.html#cb143-8" tabindex="-1"></a>  <span class="at">GeneCards =</span> dn_gcds_tbl,</span>
<span id="cb143-9"><a href="ppi-analysis.html#cb143-9" tabindex="-1"></a>  <span class="at">OpenTargets =</span> dn_otp_tbl</span>
<span id="cb143-10"><a href="ppi-analysis.html#cb143-10" tabindex="-1"></a>)</span>
<span id="cb143-11"><a href="ppi-analysis.html#cb143-11" tabindex="-1"></a></span>
<span id="cb143-12"><a href="ppi-analysis.html#cb143-12" tabindex="-1"></a><span class="do">## Lingzhi target set</span></span>
<span id="cb143-13"><a href="ppi-analysis.html#cb143-13" tabindex="-1"></a>lingzhi_df <span class="ot">&lt;-</span> <span class="fu">search_herb</span>(<span class="st">&quot;lingzhi&quot;</span>, <span class="at">type =</span> <span class="st">&quot;Herb_pinyin_name&quot;</span>)</span>
<span id="cb143-14"><a href="ppi-analysis.html#cb143-14" tabindex="-1"></a>lingzhi_w <span class="ot">&lt;-</span> <span class="fu">prepare_herb_target_weights</span>(lingzhi_df, <span class="at">method =</span> <span class="st">&quot;binary&quot;</span>)</span>
<span id="cb143-15"><a href="ppi-analysis.html#cb143-15" tabindex="-1"></a></span>
<span id="cb143-16"><a href="ppi-analysis.html#cb143-16" tabindex="-1"></a><span class="do">## set-level PPI proximity evaluation</span></span>
<span id="cb143-17"><a href="ppi-analysis.html#cb143-17" tabindex="-1"></a>set_eval <span class="ot">&lt;-</span> <span class="fu">evaluate_tcm_target_sets_by_ppi</span>(</span>
<span id="cb143-18"><a href="ppi-analysis.html#cb143-18" tabindex="-1"></a>  <span class="at">target_sets =</span> <span class="fu">list</span>(<span class="at">Lingzhi =</span> lingzhi_w),</span>
<span id="cb143-19"><a href="ppi-analysis.html#cb143-19" tabindex="-1"></a>  <span class="at">disease_targets =</span> disease_w,</span>
<span id="cb143-20"><a href="ppi-analysis.html#cb143-20" tabindex="-1"></a>  <span class="at">n_perm =</span> <span class="dv">1000</span>,</span>
<span id="cb143-21"><a href="ppi-analysis.html#cb143-21" tabindex="-1"></a>  <span class="at">seed =</span> <span class="dv">20260525</span></span>
<span id="cb143-22"><a href="ppi-analysis.html#cb143-22" tabindex="-1"></a>)</span>
<span id="cb143-23"><a href="ppi-analysis.html#cb143-23" tabindex="-1"></a></span>
<span id="cb143-24"><a href="ppi-analysis.html#cb143-24" tabindex="-1"></a>set_eval<span class="sc">$</span>result[, <span class="fu">c</span>(</span>
<span id="cb143-25"><a href="ppi-analysis.html#cb143-25" tabindex="-1"></a>  <span class="st">&quot;set&quot;</span>, <span class="st">&quot;n_targets_in_ppi&quot;</span>, <span class="st">&quot;overlap_n&quot;</span>,</span>
<span id="cb143-26"><a href="ppi-analysis.html#cb143-26" tabindex="-1"></a>  <span class="st">&quot;overlap_target_fraction&quot;</span>, <span class="st">&quot;directlink_edges&quot;</span>,</span>
<span id="cb143-27"><a href="ppi-analysis.html#cb143-27" tabindex="-1"></a>  <span class="st">&quot;first_order_target_coverage&quot;</span>, <span class="st">&quot;jaccard&quot;</span>,</span>
<span id="cb143-28"><a href="ppi-analysis.html#cb143-28" tabindex="-1"></a>  <span class="st">&quot;weighted_proximity&quot;</span>, <span class="st">&quot;z_proximity&quot;</span>, <span class="st">&quot;p_empirical&quot;</span></span>
<span id="cb143-29"><a href="ppi-analysis.html#cb143-29" tabindex="-1"></a>)]</span></code></pre></div>
<p>A simplified output may look like this:</p>
<pre class="text"><code>     set n_targets_in_ppi overlap_n overlap_target_fraction directlink_edges
 Lingzhi              894       610                  0.6823            3983

 first_order_target_coverage jaccard weighted_proximity z_proximity p_empirical
                      0.9810  0.1058             0.2325       17.88      0.001</code></pre>
<p>This result would be interpreted as follows:</p>
<ul>
<li><code>overlap_n = 610</code>: many Lingzhi targets directly overlap with DN targets.</li>
<li><code>first_order_target_coverage = 0.981</code>: most Lingzhi targets either directly overlap with the DN module or are one PPI step away from it.</li>
<li><code>jaccard = 0.1058</code>: direct set similarity is modest because the DN disease module is large.</li>
<li><code>z_proximity = 17.88</code>: Lingzhi targets are much closer to the weighted DN module than degree-matched random target sets.</li>
</ul>
<p>For comparing multiple candidate formulas or combinations, pass a named list:</p>
<div class="sourceCode" id="cb145"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb145-1"><a href="ppi-analysis.html#cb145-1" tabindex="-1"></a>multi_eval <span class="ot">&lt;-</span> <span class="fu">evaluate_tcm_target_sets_by_ppi</span>(</span>
<span id="cb145-2"><a href="ppi-analysis.html#cb145-2" tabindex="-1"></a>  <span class="at">target_sets =</span> <span class="fu">list</span>(</span>
<span id="cb145-3"><a href="ppi-analysis.html#cb145-3" tabindex="-1"></a>    <span class="at">formula_A =</span> formula_A_targets,</span>
<span id="cb145-4"><a href="ppi-analysis.html#cb145-4" tabindex="-1"></a>    <span class="at">formula_B =</span> formula_B_targets,</span>
<span id="cb145-5"><a href="ppi-analysis.html#cb145-5" tabindex="-1"></a>    <span class="at">optimized_formula =</span> optimized_targets</span>
<span id="cb145-6"><a href="ppi-analysis.html#cb145-6" tabindex="-1"></a>  ),</span>
<span id="cb145-7"><a href="ppi-analysis.html#cb145-7" tabindex="-1"></a>  <span class="at">disease_targets =</span> disease_w,</span>
<span id="cb145-8"><a href="ppi-analysis.html#cb145-8" tabindex="-1"></a>  <span class="at">n_perm =</span> <span class="dv">1000</span></span>
<span id="cb145-9"><a href="ppi-analysis.html#cb145-9" tabindex="-1"></a>)</span>
<span id="cb145-10"><a href="ppi-analysis.html#cb145-10" tabindex="-1"></a></span>
<span id="cb145-11"><a href="ppi-analysis.html#cb145-11" tabindex="-1"></a>multi_eval<span class="sc">$</span>result[<span class="fu">order</span>(multi_eval<span class="sc">$</span>result<span class="sc">$</span>Rank_set), ]</span></code></pre></div>
<p>In multi-set analysis, <code>Rank_set</code> ranks target sets by <code>Score_set</code>, which is currently equal to <code>z_proximity</code>. In single-set analysis, <code>Rank_set</code> is always 1 and should not be overinterpreted; the key statistics are <code>z_proximity</code>, <code>p_empirical</code>, <code>overlap_n</code>, and <code>first_order_target_coverage</code>.</p>
<hr />
</div>
</div>
<div id="topology" class="section level2 hasAnchor" number="7.4">
<h2><span class="header-section-number">7.4</span> Topological metrics<a href="ppi-analysis.html#topology" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Topological analysis of PPI networks is fundamental for identifying disease-critical nodes. By quantifying centrality metrics such as degree, betweenness, and closeness, researchers can pinpoint hub proteins that serve as key regulators, bottleneck nodes that control information flow, and bridge proteins that connect functional modules. These topologically important nodes often represent promising therapeutic targets.</p>
<p>Traditionally, most network pharmacology studies rely on <strong>Cytoscape</strong>, which is a widely adopted desktop application, and its <strong>CytoHubba</strong> plugin<sup>[1]</sup> to compute centrality metrics for target prioritization. While effective, this workflow requires exporting data from other software, manual operation in a GUI environment, and re-importing results, which disrupts the analytical pipeline and reduces reproducibility.</p>
<p><code>TCMDATA</code> addresses these limitations with <code>compute_nodeinfo()</code>, which calculates a comprehensive set of centrality measures directly within the R ecosystem. This approach offers two key advantages:</p>
<ol style="list-style-type: decimal">
<li><strong>Workflow integration</strong> — All analyses remain in R, eliminating context-switching and ensuring full reproducibility through scripted pipelines.</li>
<li><strong>Extended metric coverage</strong> — Beyond the 11 metrics provided by CytoHubba, <code>compute_nodeinfo()</code> includes additional measures, enabling more comprehensive topological characterization.</li>
</ol>
<p>In this example, we calculate a panel of 19 topological metrics for the filtered PPI network, using the <code>score</code> edge attribute as weights where applicable:</p>
<div class="sourceCode" id="cb146"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb146-1"><a href="ppi-analysis.html#cb146-1" tabindex="-1"></a>ppi_scored <span class="ot">&lt;-</span> <span class="fu">compute_nodeinfo</span>(ppi_filtered, <span class="at">weight_attr =</span> <span class="st">&quot;score&quot;</span>)</span></code></pre></div>
<pre><code>#&gt;   |                                                                              |                                                                      |   0%  |                                                                              |                                                                      |   1%  |                                                                              |=                                                                     |   1%  |                                                                              |=                                                                     |   2%  |                                                                              |==                                                                    |   2%  |                                                                              |==                                                                    |   3%  |                                                                              |==                                                                    |   4%  |                                                                              |===                                                                   |   4%  |                                                                              |===                                                                   |   5%  |                                                                              |====                                                                  |   5%  |                                                                              |====                                                                  |   6%  |                                                                              |=====                                                                 |   6%  |                                                                              |=====                                                                 |   7%  |                                                                              |=====                                                                 |   8%  |                                                                              |======                                                                |   8%  |                                                                              |======                                                                |   9%  |                                                                              |=======                                                               |   9%  |                                                                              |=======                                                               |  10%  |                                                                              |=======                                                               |  11%  |                                                                              |========                                                              |  11%  |                                                                              |========                                                              |  12%  |                                                                              |=========                                                             |  12%  |                                                                              |=========                                                             |  13%  |                                                                              |=========                                                             |  14%  |                                                                              |==========                                                            |  14%  |                                                                              |==========                                                            |  15%  |                                                                              |===========                                                           |  15%  |                                                                              |===========                                                           |  16%  |                                                                              |============                                                          |  16%  |                                                                              |============                                                          |  17%  |                                                                              |============                                                          |  18%  |                                                                              |=============                                                         |  18%  |                                                                              |=============                                                         |  19%  |                                                                              |==============                                                        |  19%  |                                                                              |==============                                                        |  20%  |                                                                              |==============                                                        |  21%  |                                                                              |===============                                                       |  21%  |                                                                              |===============                                                       |  22%  |                                                                              |================                                                      |  22%  |                                                                              |================                                                      |  23%  |                                                                              |================                                                      |  24%  |                                                                              |=================                                                     |  24%  |                                                                              |=================                                                     |  25%  |                                                                              |==================                                                    |  25%  |                                                                              |==================                                                    |  26%  |                                                                              |===================                                                   |  26%  |                                                                              |===================                                                   |  27%  |                                                                              |===================                                                   |  28%  |                                                                              |====================                                                  |  28%  |                                                                              |====================                                                  |  29%  |                                                                              |=====================                                                 |  29%  |                                                                              |=====================                                                 |  30%  |                                                                              |=====================                                                 |  31%  |                                                                              |======================                                                |  31%  |                                                                              |======================                                                |  32%  |                                                                              |=======================                                               |  32%  |                                                                              |=======================                                               |  33%  |                                                                              |=======================                                               |  34%  |                                                                              |========================                                              |  34%  |                                                                              |========================                                              |  35%  |                                                                              |=========================                                             |  35%  |                                                                              |=========================                                             |  36%  |                                                                              |==========================                                            |  36%  |                                                                              |==========================                                            |  37%  |                                                                              |==========================                                            |  38%  |                                                                              |===========================                                           |  38%  |                                                                              |===========================                                           |  39%  |                                                                              |============================                                          |  39%  |                                                                              |============================                                          |  40%  |                                                                              |============================                                          |  41%  |                                                                              |=============================                                         |  41%  |                                                                              |=============================                                         |  42%  |                                                                              |==============================                                        |  42%  |                                                                              |==============================                                        |  43%  |                                                                              |==============================                                        |  44%  |                                                                              |===============================                                       |  44%  |                                                                              |===============================                                       |  45%  |                                                                              |================================                                      |  45%  |                                                                              |================================                                      |  46%  |                                                                              |=================================                                     |  46%  |                                                                              |=================================                                     |  47%  |                                                                              |=================================                                     |  48%  |                                                                              |==================================                                    |  48%  |                                                                              |==================================                                    |  49%  |                                                                              |===================================                                   |  49%  |                                                                              |===================================                                   |  50%  |                                                                              |===================================                                   |  51%  |                                                                              |====================================                                  |  51%  |                                                                              |====================================                                  |  52%  |                                                                              |=====================================                                 |  52%  |                                                                              |=====================================                                 |  53%  |                                                                              |=====================================                                 |  54%  |                                                                              |======================================                                |  54%  |                                                                              |======================================                                |  55%  |                                                                              |=======================================                               |  55%  |                                                                              |=======================================                               |  56%  |                                                                              |========================================                              |  56%  |                                                                              |========================================                              |  57%  |                                                                              |========================================                              |  58%  |                                                                              |=========================================                             |  58%  |                                                                              |=========================================                             |  59%  |                                                                              |==========================================                            |  59%  |                                                                              |==========================================                            |  60%  |                                                                              |==========================================                            |  61%  |                                                                              |===========================================                           |  61%  |                                                                              |===========================================                           |  62%  |                                                                              |============================================                          |  62%  |                                                                              |============================================                          |  63%  |                                                                              |============================================                          |  64%  |                                                                              |=============================================                         |  64%  |                                                                              |=============================================                         |  65%  |                                                                              |==============================================                        |  65%  |                                                                              |==============================================                        |  66%  |                                                                              |===============================================                       |  66%  |                                                                              |===============================================                       |  67%  |                                                                              |===============================================                       |  68%  |                                                                              |================================================                      |  68%  |                                                                              |================================================                      |  69%  |                                                                              |=================================================                     |  69%  |                                                                              |=================================================                     |  70%  |                                                                              |=================================================                     |  71%  |                                                                              |==================================================                    |  71%  |                                                                              |==================================================                    |  72%  |                                                                              |===================================================                   |  72%  |                                                                              |===================================================                   |  73%  |                                                                              |===================================================                   |  74%  |                                                                              |====================================================                  |  74%  |                                                                              |====================================================                  |  75%  |                                                                              |=====================================================                 |  75%  |                                                                              |=====================================================                 |  76%  |                                                                              |======================================================                |  76%  |                                                                              |======================================================                |  77%  |                                                                              |======================================================                |  78%  |                                                                              |=======================================================               |  78%  |                                                                              |=======================================================               |  79%  |                                                                              |========================================================              |  79%  |                                                                              |========================================================              |  80%  |                                                                              |========================================================              |  81%  |                                                                              |=========================================================             |  81%  |                                                                              |=========================================================             |  82%  |                                                                              |==========================================================            |  82%  |                                                                              |==========================================================            |  83%  |                                                                              |==========================================================            |  84%  |                                                                              |===========================================================           |  84%  |                                                                              |===========================================================           |  85%  |                                                                              |============================================================          |  85%  |                                                                              |============================================================          |  86%  |                                                                              |=============================================================         |  86%  |                                                                              |=============================================================         |  87%  |                                                                              |=============================================================         |  88%  |                                                                              |==============================================================        |  88%  |                                                                              |==============================================================        |  89%  |                                                                              |===============================================================       |  89%  |                                                                              |===============================================================       |  90%  |                                                                              |===============================================================       |  91%  |                                                                              |================================================================      |  91%  |                                                                              |================================================================      |  92%  |                                                                              |=================================================================     |  92%  |                                                                              |=================================================================     |  93%  |                                                                              |=================================================================     |  94%  |                                                                              |==================================================================    |  94%  |                                                                              |==================================================================    |  95%  |                                                                              |===================================================================   |  95%  |                                                                              |===================================================================   |  96%  |                                                                              |====================================================================  |  96%  |                                                                              |====================================================================  |  97%  |                                                                              |====================================================================  |  98%  |                                                                              |===================================================================== |  98%  |                                                                              |===================================================================== |  99%  |                                                                              |======================================================================|  99%  |                                                                              |======================================================================| 100%</code></pre>
<div class="sourceCode" id="cb148"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb148-1"><a href="ppi-analysis.html#cb148-1" tabindex="-1"></a>ppi_scored <span class="sc">|&gt;</span> <span class="fu">str</span>()</span></code></pre></div>
<pre><code>#&gt; Class &#39;igraph&#39;  hidden list of 10
#&gt;  $ : num 49
#&gt;  $ : logi FALSE
#&gt;  $ : num [1:196] 11 31 37 14 17 12 10 26 38 2 ...
#&gt;  $ : num [1:196] 0 0 1 1 1 1 1 1 1 1 ...
#&gt;  $ : NULL
#&gt;  $ : NULL
#&gt;  $ : NULL
#&gt;  $ : NULL
#&gt;  $ :List of 4
#&gt;   ..$ : num [1:3] 1 0 1
#&gt;   ..$ : Named list()
#&gt;   ..$ :List of 20
#&gt;   .. ..$ name            : chr [1:49] &quot;RELB&quot; &quot;SERPINE1&quot; &quot;CCL2&quot; &quot;EGR1&quot; ...
#&gt;   .. ..$ degree          : num [1:49] 2 9 20 12 6 5 2 7 7 6 ...
#&gt;   .. ..$ strength        : num [1:49] 1.72 7.22 17.41 10.35 5.46 ...
#&gt;   .. ..$ betweenness     : num [1:49] 0 14.513 59.5 20.977 0.167 ...
#&gt;   .. ..$ betweenness_w   : num [1:49] 0 8 16 7 0 0 0 0 19 0 ...
#&gt;   .. ..$ closeness       : num [1:49] 0.00694 0.0101 0.01282 0.01111 0.00862 ...
#&gt;   .. ..$ closeness_w     : num [1:49] 0.00608 0.00859 0.01112 0.00959 0.0078 ...
#&gt;   .. ..$ eigen_centrality: num [1:49] 0.0198 0.3747 0.8258 0.3252 0.196 ...
#&gt;   .. ..$ pagerank        : num [1:49] 0.0105 0.0198 0.0416 0.0287 0.0158 ...
#&gt;   .. ..$ coreness        : num [1:49] 2 7 8 6 6 4 2 6 6 6 ...
#&gt;   .. ..$ clustering_coef : num [1:49] 1 0.611 0.453 0.545 0.933 ...
#&gt;   .. ..$ eccentricity    : num [1:49] 5 4 4 4 5 4 5 5 4 4 ...
#&gt;   .. ..$ is_articulation : logi [1:49] FALSE FALSE FALSE FALSE FALSE FALSE ...
#&gt;   .. ..$ MCC             : num [1:49] 2 5043 28584 1254 240 ...
#&gt;   .. ..$ MNC             : num [1:49] 2 8 20 12 6 5 2 7 7 6 ...
#&gt;   .. ..$ DMNC            : num [1:49] 0.308 0.641 0.528 0.527 0.666 ...
#&gt;   .. ..$ BN              : num [1:49] 0 2 22 4 0 1 0 0 1 0 ...
#&gt;   .. ..$ radiality       : num [1:49] 3.71 4.65 5.08 4.83 4.29 ...
#&gt;   .. ..$ Stress          : num [1:49] 0 88 418 139 1 26 0 10 90 1 ...
#&gt;   .. ..$ EPC             : num [1:49] 25.7 40.4 40.6 40.5 39.9 ...
#&gt;   ..$ :List of 1
#&gt;   .. ..$ score: num [1:196] 0.717 0.999 0.701 0.719 0.736 0.742 0.746 0.815 0.849 0.918 ...
#&gt;  $ :&lt;environment: 0x55f49c594a48&gt;</code></pre>
<p>The following metrics are computed and stored as vertex attributes:</p>
<table>
<colgroup>
<col width="32%" />
<col width="25%" />
<col width="41%" />
</colgroup>
<thead>
<tr class="header">
<th>Category</th>
<th>Metric</th>
<th>Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Local</strong></td>
<td><code>degree</code></td>
<td>Number of direct neighbors</td>
</tr>
<tr class="even">
<td></td>
<td><code>strength</code></td>
<td>Sum of incident edge weights</td>
</tr>
<tr class="odd">
<td></td>
<td><code>clustering_coef</code></td>
<td>Local clustering coefficient (transitivity)</td>
</tr>
<tr class="even">
<td></td>
<td><code>coreness</code></td>
<td>k-core decomposition level</td>
</tr>
<tr class="odd">
<td><strong>Global</strong></td>
<td><code>betweenness</code></td>
<td>Fraction of all-pairs shortest paths passing through the node</td>
</tr>
<tr class="even">
<td></td>
<td><code>closeness</code></td>
<td>Inverse of average shortest-path distance to all other nodes</td>
</tr>
<tr class="odd">
<td></td>
<td><code>eccentricity</code></td>
<td>Maximum shortest-path distance to any reachable node</td>
</tr>
<tr class="even">
<td></td>
<td><code>eigen_centrality</code></td>
<td>Influence score based on connections to high-scoring neighbors</td>
</tr>
<tr class="odd">
<td></td>
<td><code>pagerank</code></td>
<td>Importance based on random-walk visitation probability</td>
</tr>
<tr class="even">
<td><strong>CytoHubba</strong><sup>[1]</sup></td>
<td><code>MCC</code></td>
<td>Maximal Clique Centrality — sum of (</td>
</tr>
<tr class="odd">
<td></td>
<td><code>MNC</code></td>
<td>Maximum Neighborhood Component — size of the largest connected component among neighbors</td>
</tr>
<tr class="even">
<td></td>
<td><code>DMNC</code></td>
<td>Density of MNC — edge density of the MNC, penalized by component size (α = 1.7)</td>
</tr>
<tr class="odd">
<td></td>
<td><code>BN</code></td>
<td>BottleNeck — frequency of being a high-flow node in shortest-path trees</td>
</tr>
<tr class="even">
<td></td>
<td><code>EPC</code></td>
<td>Edge Percolated Component — average component size under random edge removal</td>
</tr>
<tr class="odd">
<td></td>
<td><code>radiality</code></td>
<td>Radiality — average gain in reachability relative to graph diameter</td>
</tr>
<tr class="even">
<td></td>
<td><code>Stress</code></td>
<td>Stress centrality — total count of shortest paths passing through the node</td>
</tr>
</tbody>
</table>
<div id="integrated-ranking" class="section level3 hasAnchor" number="7.4.1">
<h3><span class="header-section-number">7.4.1</span> Integrated ranking<a href="ppi-analysis.html#integrated-ranking" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p><code>rank_ppi_nodes()</code> normalizes all selected metrics to [0, 1], applies user-defined weights (equal by default), and produces a composite score for target prioritization:</p>
<div class="sourceCode" id="cb150"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb150-1"><a href="ppi-analysis.html#cb150-1" tabindex="-1"></a>rank_res <span class="ot">&lt;-</span> <span class="fu">rank_ppi_nodes</span>(ppi_scored, <span class="at">use_weight =</span> <span class="cn">TRUE</span>)</span>
<span id="cb150-2"><a href="ppi-analysis.html#cb150-2" tabindex="-1"></a></span>
<span id="cb150-3"><a href="ppi-analysis.html#cb150-3" tabindex="-1"></a><span class="co"># Extract ranked table</span></span>
<span id="cb150-4"><a href="ppi-analysis.html#cb150-4" tabindex="-1"></a>ppi_ranked <span class="ot">&lt;-</span> rank_res<span class="sc">$</span>graph</span>
<span id="cb150-5"><a href="ppi-analysis.html#cb150-5" tabindex="-1"></a>rank_df <span class="ot">&lt;-</span> rank_res<span class="sc">$</span>table</span>
<span id="cb150-6"><a href="ppi-analysis.html#cb150-6" tabindex="-1"></a></span>
<span id="cb150-7"><a href="ppi-analysis.html#cb150-7" tabindex="-1"></a>rank_df[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>, <span class="fu">c</span>(<span class="st">&quot;name&quot;</span>, <span class="st">&quot;degree&quot;</span>, <span class="st">&quot;betweenness_w&quot;</span>, <span class="st">&quot;closeness_w&quot;</span>,</span>
<span id="cb150-8"><a href="ppi-analysis.html#cb150-8" tabindex="-1"></a>                <span class="st">&quot;MCC&quot;</span>, <span class="st">&quot;MNC&quot;</span>, <span class="st">&quot;EPC&quot;</span>, <span class="st">&quot;Score_network&quot;</span>, <span class="st">&quot;Rank_network&quot;</span>)]</span></code></pre></div>
<pre><code>#&gt;     name degree betweenness_w closeness_w   MCC MNC    EPC Score_network
#&gt; 39   IL6     27           301 0.012828644 46520  27 40.575     0.7557900
#&gt; 18 CXCL8     22           219 0.011826965 45146  20 40.575     0.6728551
#&gt; 11  IL1B     23            81 0.012135064 45534  23 40.575     0.6323832
#&gt; 3   CCL2     20            16 0.011115212 28584  20 40.575     0.6141793
#&gt; 33   JUN     20           246 0.011534103  7618  20 40.575     0.5719901
#&gt; 17   FOS     18           135 0.010750677  2563  17 40.575     0.5170816
#&gt; 37 CXCL1     14             0 0.010180263 37584  14 40.575     0.4801195
#&gt; 48  CCL4     10             0 0.008875304 30240  10 40.575     0.4380035
#&gt; 13 ICAM1     14            12 0.009497345 18144  14 40.575     0.4376745
#&gt; 27 PTGS2     14             0 0.010199193 13320  14 40.575     0.4308640
#&gt;    Rank_network
#&gt; 39            1
#&gt; 18            2
#&gt; 11            3
#&gt; 3             4
#&gt; 33            5
#&gt; 17            6
#&gt; 37            7
#&gt; 48            8
#&gt; 13            9
#&gt; 27           10</code></pre>
</div>
<div id="radar-plot-of-topological-metrics" class="section level3 hasAnchor" number="7.4.2">
<h3><span class="header-section-number">7.4.2</span> Radar plot of topological metrics<a href="ppi-analysis.html#radar-plot-of-topological-metrics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>For a target of interest, <code>get_node_profile()</code> + <code>radar_plot()</code> produces a radar chart showing its normalized centrality fingerprint across multiple dimensions:</p>
<div class="sourceCode" id="cb152"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb152-1"><a href="ppi-analysis.html#cb152-1" tabindex="-1"></a><span class="fu">library</span>(aplot)</span>
<span id="cb152-2"><a href="ppi-analysis.html#cb152-2" tabindex="-1"></a></span>
<span id="cb152-3"><a href="ppi-analysis.html#cb152-3" tabindex="-1"></a><span class="co"># Pick the top 2 ranked nodes</span></span>
<span id="cb152-4"><a href="ppi-analysis.html#cb152-4" tabindex="-1"></a>top_nodes <span class="ot">&lt;-</span> rank_df<span class="sc">$</span>name[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]</span>
<span id="cb152-5"><a href="ppi-analysis.html#cb152-5" tabindex="-1"></a></span>
<span id="cb152-6"><a href="ppi-analysis.html#cb152-6" tabindex="-1"></a>p_radar1 <span class="ot">&lt;-</span> <span class="fu">radar_plot</span>(</span>
<span id="cb152-7"><a href="ppi-analysis.html#cb152-7" tabindex="-1"></a>  <span class="fu">get_node_profile</span>(rank_df, top_nodes[<span class="dv">1</span>]),</span>
<span id="cb152-8"><a href="ppi-analysis.html#cb152-8" tabindex="-1"></a>  <span class="at">fill_color =</span> <span class="st">&quot;#A3BEDD&quot;</span>, <span class="at">line_color =</span> <span class="st">&quot;#4A7FB5&quot;</span>,</span>
<span id="cb152-9"><a href="ppi-analysis.html#cb152-9" tabindex="-1"></a>  <span class="at">title =</span> top_nodes[<span class="dv">1</span>]</span>
<span id="cb152-10"><a href="ppi-analysis.html#cb152-10" tabindex="-1"></a>)</span>
<span id="cb152-11"><a href="ppi-analysis.html#cb152-11" tabindex="-1"></a></span>
<span id="cb152-12"><a href="ppi-analysis.html#cb152-12" tabindex="-1"></a>p_radar2 <span class="ot">&lt;-</span> <span class="fu">radar_plot</span>(</span>
<span id="cb152-13"><a href="ppi-analysis.html#cb152-13" tabindex="-1"></a>  <span class="fu">get_node_profile</span>(rank_df, top_nodes[<span class="dv">2</span>]),</span>
<span id="cb152-14"><a href="ppi-analysis.html#cb152-14" tabindex="-1"></a>  <span class="at">fill_color =</span> <span class="st">&quot;#D59390&quot;</span>, <span class="at">line_color =</span> <span class="st">&quot;#B5524A&quot;</span>,</span>
<span id="cb152-15"><a href="ppi-analysis.html#cb152-15" tabindex="-1"></a>  <span class="at">title =</span> top_nodes[<span class="dv">2</span>]</span>
<span id="cb152-16"><a href="ppi-analysis.html#cb152-16" tabindex="-1"></a>)</span>
<span id="cb152-17"><a href="ppi-analysis.html#cb152-17" tabindex="-1"></a></span>
<span id="cb152-18"><a href="ppi-analysis.html#cb152-18" tabindex="-1"></a><span class="fu">plot_list</span>(p_radar1, p_radar2, <span class="at">ncol =</span> <span class="dv">2</span>)</span></code></pre></div>
<p><img src="images/ppi-radar-1.png" alt="" width="95%" style="display: block; margin: auto;" /></p>
<hr />
</div>
<div id="heatmap-of-topological-metrics" class="section level3 hasAnchor" number="7.4.3">
<h3><span class="header-section-number">7.4.3</span> Heatmap of topological metrics<a href="ppi-analysis.html#heatmap-of-topological-metrics" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The heatmap provides a global overview of selected nodes across multiple topological metrics simultaneously. <code>plot_node_heatmap()</code> generates a Z-score normalized heatmap using <code>ComplexHeatmap</code>, with hierarchical clustering to reveal nodes with similar centrality profiles:</p>
<div class="sourceCode" id="cb153"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb153-1"><a href="ppi-analysis.html#cb153-1" tabindex="-1"></a><span class="co"># Select key metrics for visualization</span></span>
<span id="cb153-2"><a href="ppi-analysis.html#cb153-2" tabindex="-1"></a>selected_cols <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">&quot;degree&quot;</span>, <span class="st">&quot;betweenness&quot;</span>, <span class="st">&quot;closeness&quot;</span>, <span class="st">&quot;MCC&quot;</span>, <span class="st">&quot;MNC&quot;</span>, </span>
<span id="cb153-3"><a href="ppi-analysis.html#cb153-3" tabindex="-1"></a>                   <span class="st">&quot;DMNC&quot;</span>, <span class="st">&quot;EPC&quot;</span>, <span class="st">&quot;radiality&quot;</span>, <span class="st">&quot;Stress&quot;</span>)</span>
<span id="cb153-4"><a href="ppi-analysis.html#cb153-4" tabindex="-1"></a></span>
<span id="cb153-5"><a href="ppi-analysis.html#cb153-5" tabindex="-1"></a><span class="fu">plot_node_heatmap</span>(rank_df, <span class="at">select_cols =</span> selected_cols)</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-heatmap-1.png" alt="" width="95%" style="display: block; margin: auto;" /></p>
<hr />
</div>
</div>
<div id="clustering" class="section level2 hasAnchor" number="7.5">
<h2><span class="header-section-number">7.5</span> Community detection<a href="ppi-analysis.html#clustering" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Identifying densely connected subnetworks (modules) helps reveal functional protein complexes and signaling cascades. <code>TCMDATA</code> supports four complementary algorithms.</p>
<div id="louvain-modularity-optimization" class="section level3 hasAnchor" number="7.5.1">
<h3><span class="header-section-number">7.5.1</span> Louvain modularity optimization<a href="ppi-analysis.html#louvain-modularity-optimization" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Louvain algorithm<sup>[3]</sup> is a fast and scalable community detection method that optimizes network modularity through a hierarchical, greedy approach. It iteratively assigns nodes to communities that maximize the modularity gain, then aggregates communities into super-nodes and repeats the process. Due to its computational efficiency and ability to handle large-scale networks, Louvain has become one of the most popular algorithms for detecting functional modules in biological networks.</p>
<div class="sourceCode" id="cb154"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb154-1"><a href="ppi-analysis.html#cb154-1" tabindex="-1"></a>ppi_louvain <span class="ot">&lt;-</span> <span class="fu">run_louvain</span>(ppi_scored, <span class="at">resolution =</span> <span class="fl">1.0</span>)</span>
<span id="cb154-2"><a href="ppi-analysis.html#cb154-2" tabindex="-1"></a>louvain_scores <span class="ot">&lt;-</span> <span class="fu">add_cluster_score</span>(ppi_louvain, <span class="at">cluster_attr =</span> <span class="st">&quot;louvain_cluster&quot;</span>, <span class="at">min_size =</span> <span class="dv">3</span>)</span>
<span id="cb154-3"><a href="ppi-analysis.html#cb154-3" tabindex="-1"></a></span>
<span id="cb154-4"><a href="ppi-analysis.html#cb154-4" tabindex="-1"></a><span class="fu">head</span>(louvain_scores)</span></code></pre></div>
<pre><code>#&gt;   Cluster_ID Score Nodes Edges Density                        Gene_List
#&gt; 1          2 9.810    22   103   0.446 SERPINE1, CCL2, LIF, IL1RN, IL1B
#&gt; 2          3 6.111    19    55   0.322    EGR1, EGR2, SNAI1, SOX9, FOSB
#&gt; 3          1 2.667     4     4   0.667        RELB, BIRC3, NFKB2, TRAF1
#&gt;                                                                                                                      Full_Genes
#&gt; 1 SERPINE1,CCL2,LIF,IL1RN,IL1B,ICAM1,IL18,VCAM1,CXCL8,SOCS3,SELE,KLRD1,PLAUR,C5AR1,CCL20,PTGS2,CXCL1,IL6,CXCR4,FCGR3B,CCL3,CCL4
#&gt; 2                           EGR1,EGR2,SNAI1,SOX9,FOSB,CEBPB,FOS,PMAIP1,ATF3,MCL1,DUSP5,JUN,KLF4,CDKN1A,CCN1,KLF6,ZFP36,MYC,MAFF
#&gt; 3                                                                                                        RELB,BIRC3,NFKB2,TRAF1</code></pre>
<p>The <code>resolution</code> parameter controls clustering granularity: values &gt; 1 produce more, smaller clusters; values &lt; 1 yield fewer, larger clusters.</p>
</div>
<div id="mcode-molecular-complex-detection" class="section level3 hasAnchor" number="7.5.2">
<h3><span class="header-section-number">7.5.2</span> MCODE (Molecular Complex Detection)<a href="ppi-analysis.html#mcode-molecular-complex-detection" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>MCODE (Molecular Complex Detection)<sup>[2]</sup> is a classic graph-clustering algorithm specifically designed for identifying densely connected regions in PPI networks. Originally implemented as a <strong>Cytoscape plugin</strong>, MCODE has become one of the most widely adopted methods for detecting protein complexes and functional modules in network pharmacology studies.</p>
<p>The algorithm operates in three phases: (1) <strong>vertex weighting</strong> based on local neighborhood density (k-core × density), (2) <strong>seeded growth</strong> from high-scoring seed nodes, and (3) <strong>post-processing</strong> via haircut (removing singly-connected peripheral nodes) or fluff (expanding with dense neighbors).</p>
<p><code>TCMDATA</code> provides <code>run_mcode()</code>, a native R implementation of the MCODE algorithm, enabling seamless integration into scripted workflows without requiring external software. This eliminates the need to export networks to Cytoscape and manually run the plugin, significantly improving reproducibility and efficiency in PPI analysis pipelines.</p>
<div class="sourceCode" id="cb156"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb156-1"><a href="ppi-analysis.html#cb156-1" tabindex="-1"></a>ppi_mcode <span class="ot">&lt;-</span> <span class="fu">run_mcode</span>(ppi_scored, <span class="at">vwp =</span> <span class="fl">0.2</span>, <span class="at">haircut =</span> <span class="cn">TRUE</span>, <span class="at">fluff =</span> <span class="cn">FALSE</span>)</span>
<span id="cb156-2"><a href="ppi-analysis.html#cb156-2" tabindex="-1"></a>mcode_res <span class="ot">&lt;-</span> <span class="fu">get_mcode_res</span>(ppi_mcode, <span class="at">only_clusters =</span> <span class="cn">TRUE</span>)</span>
<span id="cb156-3"><a href="ppi-analysis.html#cb156-3" tabindex="-1"></a></span>
<span id="cb156-4"><a href="ppi-analysis.html#cb156-4" tabindex="-1"></a><span class="fu">head</span>(mcode_res)</span></code></pre></div>
<pre><code>#&gt;       name mcode_score  cluster module_score is_seed
#&gt; 1     IL18    6.236364 Module_1          8.6   FALSE
#&gt; 2     CCL3    6.236364 Module_1          8.6   FALSE
#&gt; 3 SERPINE1    7.000000 Module_1          8.6   FALSE
#&gt; 4    VCAM1    7.000000 Module_1          8.6   FALSE
#&gt; 5     IL1B    7.151515 Module_1          8.6   FALSE
#&gt; 6    CXCL8    7.151515 Module_1          8.6   FALSE</code></pre>
</div>
<div id="mcl-markov-clustering" class="section level3 hasAnchor" number="7.5.3">
<h3><span class="header-section-number">7.5.3</span> MCL (Markov Clustering)<a href="ppi-analysis.html#mcl-markov-clustering" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The Markov Clustering (MCL) algorithm<sup>[4]</sup> detects community structure by simulating stochastic flow (random walks) on the network. It alternates between two operations: <strong>expansion</strong> (matrix squaring to allow flow to spread) and <strong>inflation</strong> (element-wise exponentiation to strengthen strong connections and weaken weak ones). This process naturally separates the network into well-defined clusters based on flow patterns. MCL is particularly effective for PPI networks because protein complexes tend to form densely connected regions that trap random walks.</p>
<div class="sourceCode" id="cb158"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb158-1"><a href="ppi-analysis.html#cb158-1" tabindex="-1"></a>ppi_mcl <span class="ot">&lt;-</span> <span class="fu">run_MCL</span>(ppi_scored, <span class="at">inflation =</span> <span class="fl">2.5</span>)</span>
<span id="cb158-2"><a href="ppi-analysis.html#cb158-2" tabindex="-1"></a>mcl_scores <span class="ot">&lt;-</span> <span class="fu">add_cluster_score</span>(ppi_mcl, <span class="at">cluster_attr =</span> <span class="st">&quot;MCL_cluster&quot;</span>, <span class="at">min_size =</span> <span class="dv">3</span>)</span>
<span id="cb158-3"><a href="ppi-analysis.html#cb158-3" tabindex="-1"></a></span>
<span id="cb158-4"><a href="ppi-analysis.html#cb158-4" tabindex="-1"></a><span class="fu">head</span>(mcl_scores)</span></code></pre></div>
<pre><code>#&gt;   Cluster_ID  Score Nodes Edges Density                        Gene_List
#&gt; 1          7 10.211    20    97   0.511 SERPINE1, CCL2, LIF, IL1RN, IL1B
#&gt; 2          2  5.000    11    25   0.455     EGR1, EGR2, FOSB, CEBPB, FOS
#&gt; 3          5  3.200     6     8   0.533     SNAI1, SOX9, ATF3, JUN, KLF6
#&gt; 4          1  2.667     4     4   0.667        RELB, BIRC3, NFKB2, TRAF1
#&gt;                                                                                                         Full_Genes
#&gt; 1 SERPINE1,CCL2,LIF,IL1RN,IL1B,ICAM1,IL18,VCAM1,CXCL8,SOCS3,SELE,PLAUR,C5AR1,CCL20,PTGS2,CXCL1,IL6,CXCR4,CCL3,CCL4
#&gt; 2                                                        EGR1,EGR2,FOSB,CEBPB,FOS,DUSP5,KLF4,CDKN1A,CCN1,ZFP36,MYC
#&gt; 3                                                                                    SNAI1,SOX9,ATF3,JUN,KLF6,MAFF
#&gt; 4                                                                                           RELB,BIRC3,NFKB2,TRAF1</code></pre>
<p>The <code>inflation</code> parameter controls cluster granularity: higher values (e.g., 3–5) yield tighter, more granular clusters; lower values (e.g., 1.5–2) produce larger, more inclusive modules.</p>
</div>
<div id="fast-greedy-modularity-optimization" class="section level3 hasAnchor" number="7.5.4">
<h3><span class="header-section-number">7.5.4</span> Fast greedy modularity optimization<a href="ppi-analysis.html#fast-greedy-modularity-optimization" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The fast greedy algorithm<sup>[5]</sup> detects communities by greedily optimizing network modularity. It starts with each node as an individual community, then repeatedly merges the pair of communities that produces the largest modularity gain. This bottom-up strategy is efficient for undirected networks and provides a simple modularity-based alternative to Louvain for PPI module detection.</p>
<p><code>TCMDATA</code> implements this workflow through <code>run_fastgreedy()</code>, which calls <code>igraph::cluster_fast_greedy()</code> and writes the resulting membership labels back to the graph as <code>fastgreedy_cluster</code>. By default, the function uses the edge attribute <code>weight</code> as the confidence score; if <code>weight</code> is absent, it falls back to the STRING-style <code>score</code> attribute. Users can also provide a custom weight vector or set <code>weights = NA</code> for unweighted clustering.</p>
<div class="sourceCode" id="cb160"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb160-1"><a href="ppi-analysis.html#cb160-1" tabindex="-1"></a>ppi_fastgreedy <span class="ot">&lt;-</span> <span class="fu">run_fastgreedy</span>(ppi_scored)</span>
<span id="cb160-2"><a href="ppi-analysis.html#cb160-2" tabindex="-1"></a>fastgreedy_scores <span class="ot">&lt;-</span> <span class="fu">add_cluster_score</span>(</span>
<span id="cb160-3"><a href="ppi-analysis.html#cb160-3" tabindex="-1"></a>  ppi_fastgreedy,</span>
<span id="cb160-4"><a href="ppi-analysis.html#cb160-4" tabindex="-1"></a>  <span class="at">cluster_attr =</span> <span class="st">&quot;fastgreedy_cluster&quot;</span>,</span>
<span id="cb160-5"><a href="ppi-analysis.html#cb160-5" tabindex="-1"></a>  <span class="at">min_size =</span> <span class="dv">3</span></span>
<span id="cb160-6"><a href="ppi-analysis.html#cb160-6" tabindex="-1"></a>)</span>
<span id="cb160-7"><a href="ppi-analysis.html#cb160-7" tabindex="-1"></a></span>
<span id="cb160-8"><a href="ppi-analysis.html#cb160-8" tabindex="-1"></a><span class="fu">head</span>(fastgreedy_scores)</span></code></pre></div>
<pre><code>#&gt;   Cluster_ID Score Nodes Edges Density                        Gene_List
#&gt; 1          2 9.810    22   103   0.446 SERPINE1, CCL2, LIF, IL1RN, IL1B
#&gt; 2          1 6.111    19    55   0.322    EGR1, EGR2, SNAI1, SOX9, FOSB
#&gt; 3          4 2.667     4     4   0.667        RELB, BIRC3, NFKB2, TRAF1
#&gt;                                                                                                                      Full_Genes
#&gt; 1 SERPINE1,CCL2,LIF,IL1RN,IL1B,ICAM1,IL18,VCAM1,CXCL8,SOCS3,SELE,KLRD1,PLAUR,C5AR1,CCL20,PTGS2,CXCL1,IL6,CXCR4,FCGR3B,CCL3,CCL4
#&gt; 2                           EGR1,EGR2,SNAI1,SOX9,FOSB,CEBPB,FOS,PMAIP1,ATF3,MCL1,DUSP5,JUN,KLF4,CDKN1A,CCN1,KLF6,ZFP36,MYC,MAFF
#&gt; 3                                                                                                        RELB,BIRC3,NFKB2,TRAF1</code></pre>
<p>The <code>weights</code> parameter controls whether PPI confidence scores contribute to modularity optimization. For example, <code>weights = "score"</code> explicitly uses the <code>score</code> edge attribute, while <code>weights = NA</code> performs unweighted fast greedy clustering.</p>
</div>
</div>
<div id="robustness" class="section level2 hasAnchor" number="7.6">
<h2><span class="header-section-number">7.6</span> PPI network robustness analysis<a href="ppi-analysis.html#robustness" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Assessing the robustness of PPI networks to node perturbation is crucial for understanding the resilience of biological systems and identifying critical vulnerabilities. The <code>ppi_knock()</code> function simulates targeted node removal (knockout) and evaluates the impact on network integrity by comparing against randomized null models, following the drug attack model proposed by Xi et al. (2022)<sup>[6]</sup>.</p>
<div id="algorithm-overview" class="section level3 hasAnchor" number="7.6.1">
<h3><span class="header-section-number">7.6.1</span> Algorithm overview<a href="ppi-analysis.html#algorithm-overview" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The algorithm tracks four network-level topological metrics — <strong>ASPL</strong> (Average Shortest Path Length), <strong>AD</strong> (Average Degree), <strong>DC</strong> (Degree Centralization), and <strong>CC</strong> (Closeness Centrality) — and proceeds in four stages:</p>
<ol style="list-style-type: decimal">
<li><strong>Baseline</strong>: Compute the four metrics on the intact network.</li>
<li><strong>Real attack</strong>: Remove the target nodes and re-compute metrics. The Robustness Index (RI) quantifies relative change: <span class="math inline">\(RI = (M_{after} - M_{before}) / M_{before}\)</span>.</li>
<li><strong>Permutation null</strong>: Rewire the network <span class="math inline">\(n\)</span> times (preserving degree sequence), shuffle edge weights, randomly knock out the same number of nodes, and compute the random RI distribution.</li>
<li><strong>Z-score normalization</strong>: <span class="math inline">\(Z = (RI_{real} - \mu_{null}) / \sigma_{null}\)</span>, with p-values derived via normal approximation: <span class="math inline">\(p = 2\Phi(-|Z|)\)</span>.</li>
</ol>
<p>The <strong>Total Score</strong> integrates all metrics: <span class="math inline">\(Total = Z_{ASPL} - Z_{AD} - Z_{DC} - Z_{CC}\)</span>. A large positive value indicates the knocked-out targets are structurally critical. The <strong>Total P-value</strong> is derived by comparing the real combined RI against the permutation null distribution of combined RIs.</p>
</div>
<div id="example-knocking-out-il6" class="section level3 hasAnchor" number="7.6.2">
<h3><span class="header-section-number">7.6.2</span> Example: knocking out IL6<a href="ppi-analysis.html#example-knocking-out-il6" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<div class="sourceCode" id="cb162"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb162-1"><a href="ppi-analysis.html#cb162-1" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">ppi_knock</span>(ppi_scored, <span class="at">targets =</span> <span class="st">&quot;IL6&quot;</span>, <span class="at">n_perm =</span> <span class="dv">100</span>)</span>
<span id="cb162-2"><a href="ppi-analysis.html#cb162-2" tabindex="-1"></a>res<span class="sc">$</span>Summary</span></code></pre></div>
<pre><code>#&gt;   Metric  Baseline   Post_KO      Raw_RI    Mu_Random   Sd_Random Normalized_RI
#&gt; 1   ASPL 2.7306271 2.8533420  0.04494018  0.001669616 0.010447079      4.141881
#&gt; 2     AD 8.0000000 7.0416667 -0.11979167 -0.022552083 0.038223524     -2.543972
#&gt; 3     DC 0.3958333 0.3182624 -0.19596865 -0.012564390 0.046719451     -3.925651
#&gt; 4     CC 0.4673347 0.4485911 -0.04010743 -0.001194393 0.009824485     -3.960822
#&gt;         Pvalue
#&gt; 1 3.444689e-05
#&gt; 2 1.095998e-02
#&gt; 3 8.649551e-05
#&gt; 4 7.469231e-05</code></pre>
<div class="sourceCode" id="cb164"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb164-1"><a href="ppi-analysis.html#cb164-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total Score:&quot;</span>, res<span class="sc">$</span>Total_Score, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; Total Score: 14.57233</code></pre>
<div class="sourceCode" id="cb166"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb166-1"><a href="ppi-analysis.html#cb166-1" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">&quot;Total P-value:&quot;</span>, res<span class="sc">$</span>Total_Pvalue, <span class="st">&quot;</span><span class="sc">\n</span><span class="st">&quot;</span>)</span></code></pre></div>
<pre><code>#&gt; Total P-value: 5.273783e-05</code></pre>
<p>The results show that removing IL6 causes ASPL to increase (network paths become longer) while AD, DC, and CC decrease (connectivity drops), all deviating significantly from the random null (|Z| &gt; 1.96, p &lt; 0.05 for all metrics). The high Total Score (with a highly significant p-value) confirms IL6 as a structurally critical hub in this PPI network.</p>
</div>
<div id="visualization-before-vs.-after-knockout" class="section level3 hasAnchor" number="7.6.3">
<h3><span class="header-section-number">7.6.3</span> Visualization: before vs. after knockout<a href="ppi-analysis.html#visualization-before-vs.-after-knockout" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>To visually compare network topology before and after knockout, we plot the intact network (with the target highlighted in red) alongside the post-knockout network:</p>
<div class="sourceCode" id="cb168"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb168-1"><a href="ppi-analysis.html#cb168-1" tabindex="-1"></a><span class="fu">library</span>(ggtangle)</span>
<span id="cb168-2"><a href="ppi-analysis.html#cb168-2" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb168-3"><a href="ppi-analysis.html#cb168-3" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb168-4"><a href="ppi-analysis.html#cb168-4" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb168-5"><a href="ppi-analysis.html#cb168-5" tabindex="-1"></a><span class="fu">library</span>(aplot)</span>
<span id="cb168-6"><a href="ppi-analysis.html#cb168-6" tabindex="-1"></a></span>
<span id="cb168-7"><a href="ppi-analysis.html#cb168-7" tabindex="-1"></a>target_node <span class="ot">&lt;-</span> <span class="st">&quot;IL6&quot;</span></span>
<span id="cb168-8"><a href="ppi-analysis.html#cb168-8" tabindex="-1"></a></span>
<span id="cb168-9"><a href="ppi-analysis.html#cb168-9" tabindex="-1"></a><span class="do">## prepare before / after igraph objects</span></span>
<span id="cb168-10"><a href="ppi-analysis.html#cb168-10" tabindex="-1"></a>g_before <span class="ot">&lt;-</span> ppi_ranked</span>
<span id="cb168-11"><a href="ppi-analysis.html#cb168-11" tabindex="-1"></a><span class="fu">V</span>(g_before)<span class="sc">$</span>is_target <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(<span class="fu">V</span>(g_before)<span class="sc">$</span>name <span class="sc">==</span> target_node, <span class="st">&quot;Target&quot;</span>, <span class="st">&quot;Other&quot;</span>)</span>
<span id="cb168-12"><a href="ppi-analysis.html#cb168-12" tabindex="-1"></a></span>
<span id="cb168-13"><a href="ppi-analysis.html#cb168-13" tabindex="-1"></a>g_after <span class="ot">&lt;-</span> <span class="fu">delete_vertices</span>(g_before, target_node)</span>
<span id="cb168-14"><a href="ppi-analysis.html#cb168-14" tabindex="-1"></a></span>
<span id="cb168-15"><a href="ppi-analysis.html#cb168-15" tabindex="-1"></a><span class="do">## network before knockout</span></span>
<span id="cb168-16"><a href="ppi-analysis.html#cb168-16" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb168-17"><a href="ppi-analysis.html#cb168-17" tabindex="-1"></a>p_before <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(g_before, <span class="at">layout =</span> <span class="st">&quot;fr&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-18"><a href="ppi-analysis.html#cb168-18" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.10</span>, <span class="at">color =</span> <span class="st">&quot;grey65&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-19"><a href="ppi-analysis.html#cb168-19" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> is_target, <span class="at">size =</span> degree), <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb168-20"><a href="ppi-analysis.html#cb168-20" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">max.overlaps =</span> <span class="dv">25</span>,</span>
<span id="cb168-21"><a href="ppi-analysis.html#cb168-21" tabindex="-1"></a>                  <span class="at">segment.alpha =</span> <span class="fl">0.3</span>, <span class="at">fontface =</span> <span class="st">&quot;italic&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-22"><a href="ppi-analysis.html#cb168-22" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="at">Other =</span> <span class="st">&quot;#56B4E9&quot;</span>, <span class="at">Target =</span> <span class="st">&quot;#D55E00&quot;</span>),</span>
<span id="cb168-23"><a href="ppi-analysis.html#cb168-23" tabindex="-1"></a>                     <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-24"><a href="ppi-analysis.html#cb168-24" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">8</span>), <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-25"><a href="ppi-analysis.html#cb168-25" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">&quot;Before knockout&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-26"><a href="ppi-analysis.html#cb168-26" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb168-27"><a href="ppi-analysis.html#cb168-27" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb168-28"><a href="ppi-analysis.html#cb168-28" tabindex="-1"></a></span>
<span id="cb168-29"><a href="ppi-analysis.html#cb168-29" tabindex="-1"></a><span class="do">## network after knockout</span></span>
<span id="cb168-30"><a href="ppi-analysis.html#cb168-30" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb168-31"><a href="ppi-analysis.html#cb168-31" tabindex="-1"></a>p_after <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(g_after, <span class="at">layout =</span> <span class="st">&quot;fr&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-32"><a href="ppi-analysis.html#cb168-32" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.10</span>, <span class="at">color =</span> <span class="st">&quot;grey65&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-33"><a href="ppi-analysis.html#cb168-33" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> degree, <span class="at">size =</span> Score_network), <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb168-34"><a href="ppi-analysis.html#cb168-34" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">max.overlaps =</span> <span class="dv">25</span>,</span>
<span id="cb168-35"><a href="ppi-analysis.html#cb168-35" tabindex="-1"></a>                  <span class="at">segment.alpha =</span> <span class="fl">0.3</span>, <span class="at">fontface =</span> <span class="st">&quot;italic&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-36"><a href="ppi-analysis.html#cb168-36" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">&quot;#56B4E9&quot;</span>, <span class="at">high =</span> <span class="st">&quot;#D55E00&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Degree&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-37"><a href="ppi-analysis.html#cb168-37" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">8</span>), <span class="at">name =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb168-38"><a href="ppi-analysis.html#cb168-38" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">&quot;After knockout (&quot;</span>, target_node, <span class="st">&quot; removed)&quot;</span>)) <span class="sc">+</span></span>
<span id="cb168-39"><a href="ppi-analysis.html#cb168-39" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb168-40"><a href="ppi-analysis.html#cb168-40" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">plot.title =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="fl">0.5</span>, <span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">12</span>))</span>
<span id="cb168-41"><a href="ppi-analysis.html#cb168-41" tabindex="-1"></a></span>
<span id="cb168-42"><a href="ppi-analysis.html#cb168-42" tabindex="-1"></a><span class="fu">plot_list</span>(p_before, p_after, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>))</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-knock-vis-1.png" alt="" width="100%" style="display: block; margin: auto;" /></p>
<ul>
<li><strong>Panel A</strong> shows the intact network with IL6 highlighted in red, revealing its central position and high degree.</li>
<li><strong>Panel B</strong> shows the network after removing IL6 — the loss of its connections visibly fragments local connectivity.</li>
</ul>
</div>
</div>
<div id="ppi-vis" class="section level2 hasAnchor" number="7.7">
<h2><span class="header-section-number">7.7</span> PPI network visualization<a href="ppi-analysis.html#ppi-vis" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>High-quality network visualization is essential for interpreting PPI analysis results and preparing publication-ready figures. While Cytoscape remains a popular choice for network visualization, it requires manual GUI operations that are difficult to reproduce and integrate into automated workflows.</p>
<p><code>ggtangle</code><sup>[7]</sup> addresses these limitations by providing a <code>ggplot2</code>-native framework for network rendering. Key advantages include:</p>
<ul>
<li><strong>Full <code>ggplot2</code> compatibility</strong> — Seamless integration with the grammar of graphics; supports all <code>ggplot2</code> themes, scales, and annotations.</li>
<li><strong>Reproducibility</strong> — All visualizations are generated programmatically, ensuring consistent results across runs.</li>
<li><strong>Publication-ready output</strong> — Fine-grained control over node aesthetics, edge styling, and layout algorithms for SCI-standard figures.</li>
<li><strong>Direct <code>igraph</code> support</strong> — Accepts <code>igraph</code> objects directly without format conversion.</li>
</ul>
<div id="basic-network-with-topological-mapping" class="section level3 hasAnchor" number="7.7.1">
<h3><span class="header-section-number">7.7.1</span> Basic network with topological mapping<a href="ppi-analysis.html#basic-network-with-topological-mapping" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The following example maps node <strong>degree</strong> to color and <strong>composite score</strong> to size, using the Fruchterman-Reingold force-directed layout:</p>
<div class="sourceCode" id="cb169"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb169-1"><a href="ppi-analysis.html#cb169-1" tabindex="-1"></a><span class="fu">library</span>(ggtangle)</span>
<span id="cb169-2"><a href="ppi-analysis.html#cb169-2" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb169-3"><a href="ppi-analysis.html#cb169-3" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb169-4"><a href="ppi-analysis.html#cb169-4" tabindex="-1"></a></span>
<span id="cb169-5"><a href="ppi-analysis.html#cb169-5" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb169-6"><a href="ppi-analysis.html#cb169-6" tabindex="-1"></a><span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;fr&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-7"><a href="ppi-analysis.html#cb169-7" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.12</span>, <span class="at">color =</span> <span class="st">&quot;grey60&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-8"><a href="ppi-analysis.html#cb169-8" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> degree, <span class="at">size =</span> Score_network), <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb169-9"><a href="ppi-analysis.html#cb169-9" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">max.overlaps =</span> <span class="dv">30</span>, <span class="at">segment.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb169-10"><a href="ppi-analysis.html#cb169-10" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">&quot;#56B4E9&quot;</span>, <span class="at">high =</span> <span class="st">&quot;#D55E00&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Degree&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-11"><a href="ppi-analysis.html#cb169-11" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">8</span>), <span class="at">name =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb169-12"><a href="ppi-analysis.html#cb169-12" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb169-13"><a href="ppi-analysis.html#cb169-13" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb169-14"><a href="ppi-analysis.html#cb169-14" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb169-15"><a href="ppi-analysis.html#cb169-15" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb169-16"><a href="ppi-analysis.html#cb169-16" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-net-basic-1.png" alt="" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="community-colored-network" class="section level3 hasAnchor" number="7.7.2">
<h3><span class="header-section-number">7.7.2</span> Community-colored network<a href="ppi-analysis.html#community-colored-network" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Overlaying cluster assignments reveals modular organization. Hub nodes (top 15% by degree) are labeled using <code>ggrepel</code> to avoid text overlap:</p>
<div class="sourceCode" id="cb170"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb170-1"><a href="ppi-analysis.html#cb170-1" tabindex="-1"></a><span class="fu">library</span>(ggrepel)</span>
<span id="cb170-2"><a href="ppi-analysis.html#cb170-2" tabindex="-1"></a></span>
<span id="cb170-3"><a href="ppi-analysis.html#cb170-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb170-4"><a href="ppi-analysis.html#cb170-4" tabindex="-1"></a><span class="fu">ggplot</span>(ppi_louvain, <span class="at">layout =</span> <span class="st">&quot;fr&quot;</span>) <span class="sc">+</span></span>
<span id="cb170-5"><a href="ppi-analysis.html#cb170-5" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.10</span>, <span class="at">color =</span> <span class="st">&quot;grey65&quot;</span>) <span class="sc">+</span></span>
<span id="cb170-6"><a href="ppi-analysis.html#cb170-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> louvain_cluster, <span class="at">size =</span> degree), <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb170-7"><a href="ppi-analysis.html#cb170-7" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">max.overlaps =</span> <span class="dv">30</span>, <span class="at">segment.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb170-8"><a href="ppi-analysis.html#cb170-8" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">&quot;Set2&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Module&quot;</span>) <span class="sc">+</span></span>
<span id="cb170-9"><a href="ppi-analysis.html#cb170-9" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">9</span>), <span class="at">name =</span> <span class="st">&quot;Degree&quot;</span>) <span class="sc">+</span></span>
<span id="cb170-10"><a href="ppi-analysis.html#cb170-10" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb170-11"><a href="ppi-analysis.html#cb170-11" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb170-12"><a href="ppi-analysis.html#cb170-12" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb170-13"><a href="ppi-analysis.html#cb170-13" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb170-14"><a href="ppi-analysis.html#cb170-14" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-net-louvain-1.png" alt="" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="hub-centric-star-layout" class="section level3 hasAnchor" number="7.7.3">
<h3><span class="header-section-number">7.7.3</span> Hub-centric star layout<a href="ppi-analysis.html#hub-centric-star-layout" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>The star layout positions the highest-degree node at the center, emphasizing hub–spoke relationships:</p>
<div class="sourceCode" id="cb171"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb171-1"><a href="ppi-analysis.html#cb171-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb171-2"><a href="ppi-analysis.html#cb171-2" tabindex="-1"></a><span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;star&quot;</span>) <span class="sc">+</span></span>
<span id="cb171-3"><a href="ppi-analysis.html#cb171-3" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.12</span>, <span class="at">color =</span> <span class="st">&quot;grey60&quot;</span>) <span class="sc">+</span></span>
<span id="cb171-4"><a href="ppi-analysis.html#cb171-4" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> Score_network, <span class="at">size =</span> degree), <span class="at">alpha =</span> <span class="fl">0.85</span>) <span class="sc">+</span></span>
<span id="cb171-5"><a href="ppi-analysis.html#cb171-5" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="fl">2.5</span>, <span class="at">max.overlaps =</span> <span class="dv">30</span>, <span class="at">segment.alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb171-6"><a href="ppi-analysis.html#cb171-6" tabindex="-1"></a>  <span class="fu">scale_color_viridis_c</span>(<span class="at">option =</span> <span class="st">&quot;C&quot;</span>, <span class="at">name =</span> <span class="st">&quot;Score&quot;</span>) <span class="sc">+</span></span>
<span id="cb171-7"><a href="ppi-analysis.html#cb171-7" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">10</span>), <span class="at">name =</span> <span class="st">&quot;Degree&quot;</span>) <span class="sc">+</span></span>
<span id="cb171-8"><a href="ppi-analysis.html#cb171-8" tabindex="-1"></a>  <span class="fu">theme_void</span>() <span class="sc">+</span></span>
<span id="cb171-9"><a href="ppi-analysis.html#cb171-9" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb171-10"><a href="ppi-analysis.html#cb171-10" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">&quot;right&quot;</span>,</span>
<span id="cb171-11"><a href="ppi-analysis.html#cb171-11" tabindex="-1"></a>    <span class="at">legend.title =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">&quot;bold&quot;</span>, <span class="at">size =</span> <span class="dv">10</span>)</span>
<span id="cb171-12"><a href="ppi-analysis.html#cb171-12" tabindex="-1"></a>  )</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-net-star-1.png" alt="" width="95%" style="display: block; margin: auto;" /></p>
</div>
<div id="layout-algorithm-comparison" class="section level3 hasAnchor" number="7.7.4">
<h3><span class="header-section-number">7.7.4</span> Layout algorithm comparison<a href="ppi-analysis.html#layout-algorithm-comparison" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Different layouts suit different analytical purposes. The following comparison illustrates four common algorithms:</p>
<div class="sourceCode" id="cb172"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb172-1"><a href="ppi-analysis.html#cb172-1" tabindex="-1"></a><span class="fu">library</span>(aplot)</span>
<span id="cb172-2"><a href="ppi-analysis.html#cb172-2" tabindex="-1"></a></span>
<span id="cb172-3"><a href="ppi-analysis.html#cb172-3" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2025</span>)</span>
<span id="cb172-4"><a href="ppi-analysis.html#cb172-4" tabindex="-1"></a>base_layers <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb172-5"><a href="ppi-analysis.html#cb172-5" tabindex="-1"></a>  <span class="fu">geom_edge</span>(<span class="at">alpha =</span> <span class="fl">0.10</span>, <span class="at">color =</span> <span class="st">&quot;grey65&quot;</span>),</span>
<span id="cb172-6"><a href="ppi-analysis.html#cb172-6" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">color =</span> degree, <span class="at">size =</span> Score_network), <span class="at">alpha =</span> <span class="fl">0.85</span>),</span>
<span id="cb172-7"><a href="ppi-analysis.html#cb172-7" tabindex="-1"></a>  <span class="fu">geom_text_repel</span>(<span class="fu">aes</span>(<span class="at">label =</span> name), <span class="at">size =</span> <span class="dv">2</span>, <span class="at">max.overlaps =</span> <span class="dv">25</span>, <span class="at">segment.alpha =</span> <span class="fl">0.3</span>),</span>
<span id="cb172-8"><a href="ppi-analysis.html#cb172-8" tabindex="-1"></a>  <span class="fu">scale_color_gradient</span>(<span class="at">low =</span> <span class="st">&quot;#56B4E9&quot;</span>, <span class="at">high =</span> <span class="st">&quot;#D55E00&quot;</span>, <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>),</span>
<span id="cb172-9"><a href="ppi-analysis.html#cb172-9" tabindex="-1"></a>  <span class="fu">scale_size_continuous</span>(<span class="at">range =</span> <span class="fu">c</span>(<span class="fl">1.5</span>, <span class="dv">6</span>), <span class="at">guide =</span> <span class="st">&quot;none&quot;</span>),</span>
<span id="cb172-10"><a href="ppi-analysis.html#cb172-10" tabindex="-1"></a>  <span class="fu">theme_void</span>()</span>
<span id="cb172-11"><a href="ppi-analysis.html#cb172-11" tabindex="-1"></a>)</span>
<span id="cb172-12"><a href="ppi-analysis.html#cb172-12" tabindex="-1"></a></span>
<span id="cb172-13"><a href="ppi-analysis.html#cb172-13" tabindex="-1"></a>p_fr     <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;fr&quot;</span>)     <span class="sc">+</span> base_layers</span>
<span id="cb172-14"><a href="ppi-analysis.html#cb172-14" tabindex="-1"></a>p_kk     <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;kk&quot;</span>)     <span class="sc">+</span> base_layers</span>
<span id="cb172-15"><a href="ppi-analysis.html#cb172-15" tabindex="-1"></a>p_nicely <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;nicely&quot;</span>) <span class="sc">+</span> base_layers</span>
<span id="cb172-16"><a href="ppi-analysis.html#cb172-16" tabindex="-1"></a>p_star   <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(ppi_ranked, <span class="at">layout =</span> <span class="st">&quot;star&quot;</span>)   <span class="sc">+</span> base_layers</span>
<span id="cb172-17"><a href="ppi-analysis.html#cb172-17" tabindex="-1"></a></span>
<span id="cb172-18"><a href="ppi-analysis.html#cb172-18" tabindex="-1"></a><span class="fu">plot_list</span>(p_fr, p_kk, p_nicely, p_star, <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>))</span></code></pre></div>
<p><img src="TCMDATA_files/figure-html/ppi-net-layouts-1.png" alt="" width="100%" style="display: block; margin: auto;" /></p>
<table>
<colgroup>
<col width="18%" />
<col width="21%" />
<col width="34%" />
<col width="26%" />
</colgroup>
<thead>
<tr class="header">
<th>Panel</th>
<th>Layout</th>
<th>Description</th>
<th>Best for</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>Fruchterman-Reingold</td>
<td>Force-directed; minimizes edge crossings</td>
<td>Dense networks with many edges</td>
</tr>
<tr class="even">
<td>B</td>
<td>Kamada-Kawai</td>
<td>Energy-based; preserves graph distances</td>
<td>Medium networks with clear clusters</td>
</tr>
<tr class="odd">
<td>C</td>
<td>Nicely</td>
<td>Automatic selection by <code>igraph</code></td>
<td>General-purpose visualization</td>
</tr>
<tr class="even">
<td>D</td>
<td>Star</td>
<td>Hub at center, others radially arranged</td>
<td>Hub-centric topology analysis</td>
</tr>
</tbody>
</table>
<hr />
</div>
</div>
<div id="references-4" class="section level2 hasAnchor" number="7.8">
<h2><span class="header-section-number">7.8</span> References<a href="ppi-analysis.html#references-4" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<ol style="list-style-type: decimal">
<li><p>Chin CH, Chen SH, Wu HH, Ho CW, Ko MT, Lin CY. cytoHubba: identifying hub objects and sub-networks from complex interactome. <em>BMC Systems Biology</em> (2014), 8(Suppl 4), S11. doi: <a href="https://doi.org/10.1186/1752-0509-8-S4-S11">10.1186/1752-0509-8-S4-S11</a>.</p></li>
<li><p>Bader GD, Hogue CW. An automated method for finding molecular complexes in large protein interaction networks. <em>BMC Bioinformatics</em> (2003), 4, 2. doi: <a href="https://doi.org/10.1186/1471-2105-4-2">10.1186/1471-2105-4-2</a>.</p></li>
<li><p>Blondel VD, Guillaume JL, Lambiotte R, Lefebvre E. Fast unfolding of communities in large networks. <em>Journal of Statistical Mechanics: Theory and Experiment</em> (2008), 2008(10), P10008. doi: <a href="https://doi.org/10.1088/1742-5468/2008/10/P10008">10.1088/1742-5468/2008/10/P10008</a>.</p></li>
<li><p>van Dongen S. Graph clustering via a discrete uncoupling process. <em>SIAM Journal on Matrix Analysis and Applications</em> (2008), 30(1), 121–141. doi: <a href="https://doi.org/10.1137/040608635">10.1137/040608635</a>.</p></li>
<li><p>Clauset A, Newman MEJ, Moore C. Finding community structure in very large networks. <em>Physical Review E</em> (2004), 70(6), 066111. doi: <a href="https://doi.org/10.1103/PhysRevE.70.066111">10.1103/PhysRevE.70.066111</a>.</p></li>
<li><p>Xi Y, et al. Exploration of the Specific Pathology of HXMM Tablet Against Retinal Injury Based on Drug Attack Model to Network Robustness. <em>Frontiers in Pharmacology</em> (2022), 13, 826535. doi: <a href="https://doi.org/10.3389/fphar.2022.826535">10.3389/fphar.2022.826535</a>.</p></li>
<li><h2 id="yu-g.-ggtangle-draw-network-and-phylogenetic-tree-using-grammar-of-graphics.-r-package.-doi-10.32614cran.package.ggtangle." class="hasAnchor">Yu G. ggtangle: Draw Network and Phylogenetic Tree Using Grammar of Graphics. R package. doi: <a href="https://doi.org/10.32614/CRAN.package.ggtangle">10.32614/CRAN.package.ggtangle</a>.<a href="ppi-analysis.html#yu-g.-ggtangle-draw-network-and-phylogenetic-tree-using-grammar-of-graphics.-r-package.-doi-10.32614cran.package.ggtangle." class="anchor-section" aria-label="Anchor link to header"></a></h2></li>
</ol>
</div>
<div id="session-information-6" class="section level2 hasAnchor" number="7.9">
<h2><span class="header-section-number">7.9</span> Session information<a href="ppi-analysis.html#session-information-6" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div class="sourceCode" id="cb173"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb173-1"><a href="ppi-analysis.html#cb173-1" tabindex="-1"></a><span class="fu">sessionInfo</span>()</span></code></pre></div>
<pre><code>#&gt; R version 4.6.0 (2026-04-24)
#&gt; Platform: x86_64-pc-linux-gnu
#&gt; Running under: Ubuntu 24.04.4 LTS
#&gt; 
#&gt; Matrix products: default
#&gt; BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
#&gt; LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.26.so;  LAPACK version 3.12.0
#&gt; 
#&gt; locale:
#&gt;  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
#&gt;  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
#&gt;  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
#&gt;  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
#&gt;  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
#&gt; [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#&gt; 
#&gt; time zone: UTC
#&gt; tzcode source: system (glibc)
#&gt; 
#&gt; attached base packages:
#&gt; [1] stats4    stats     graphics  grDevices utils     datasets  methods  
#&gt; [8] base     
#&gt; 
#&gt; other attached packages:
#&gt;  [1] org.Hs.eg.db_3.23.1    AnnotationDbi_1.74.0   IRanges_2.46.0        
#&gt;  [4] S4Vectors_0.50.1       Biobase_2.72.0         BiocGenerics_0.58.1   
#&gt;  [7] generics_0.1.4         clusterProfiler_4.20.0 aplot_0.2.9           
#&gt; [10] ggrepel_0.9.8          ggtangle_0.1.2         igraph_2.3.1          
#&gt; [13] ggplot2_4.0.3          dplyr_1.2.1            ivolcano_0.0.5        
#&gt; [16] enrichplot_1.32.0      TCMDATA_0.1.0         
#&gt; 
#&gt; loaded via a namespace (and not attached):
#&gt;   [1] RColorBrewer_1.1-3      rstudioapi_0.18.0       jsonlite_2.0.0         
#&gt;   [4] shape_1.4.6.1           tidydr_0.0.6            magrittr_2.0.5         
#&gt;   [7] farver_2.1.2            rmarkdown_2.31          GlobalOptions_0.1.4    
#&gt;  [10] fs_2.1.0                vctrs_0.7.3             memoise_2.0.1          
#&gt;  [13] ggtree_4.2.0            htmltools_0.5.9         gridGraphics_0.5-1     
#&gt;  [16] sass_0.4.10             bslib_0.11.0            htmlwidgets_1.6.4      
#&gt;  [19] plyr_1.8.9              httr2_1.2.2             cachem_1.1.0           
#&gt;  [22] lifecycle_1.0.5         iterators_1.0.14        pkgconfig_2.0.3        
#&gt;  [25] Matrix_1.7-5            R6_2.6.1                fastmap_1.2.0          
#&gt;  [28] gson_0.1.0              clue_0.3-68             digest_0.6.39          
#&gt;  [31] colorspace_2.1-2        ggnewscale_0.5.2        patchwork_1.3.2        
#&gt;  [34] aisdk_1.4.8             ps_1.9.3                RSQLite_3.53.1         
#&gt;  [37] labeling_0.4.3          httr_1.4.8              polyclip_1.10-7        
#&gt;  [40] compiler_4.6.0          bit64_4.8.2             fontquiver_0.2.1       
#&gt;  [43] withr_3.0.2             doParallel_1.0.17       S7_0.2.2               
#&gt;  [46] DBI_1.3.0               ggforce_0.5.0           MASS_7.3-65            
#&gt;  [49] rappdirs_0.3.4          rjson_0.2.23            tools_4.6.0            
#&gt;  [52] ape_5.8-1               scatterpie_0.2.6        glue_1.8.1             
#&gt;  [55] callr_3.7.6             nlme_3.1-169            GOSemSim_2.38.0        
#&gt;  [58] grid_4.6.0              ggvenn_0.1.19           cluster_2.1.8.2        
#&gt;  [61] reshape2_1.4.5          gtable_0.3.6            tidyr_1.3.2            
#&gt;  [64] XVector_0.52.0          foreach_1.5.2           pillar_1.11.1          
#&gt;  [67] stringr_1.6.0           yulab.utils_0.2.4       circlize_0.4.18        
#&gt;  [70] splines_4.6.0           tweenr_2.0.3            treeio_1.36.1          
#&gt;  [73] lattice_0.22-9          bit_4.6.0               tidyselect_1.2.1       
#&gt;  [76] fontLiberation_0.1.0    GO.db_3.23.1            ComplexHeatmap_2.28.0  
#&gt;  [79] Biostrings_2.80.1       knitr_1.51              fontBitstreamVera_0.1.1
#&gt;  [82] gridExtra_2.3           bookdown_0.46           Seqinfo_1.2.0          
#&gt;  [85] xfun_0.57               matrixStats_1.5.0       stringi_1.8.7          
#&gt;  [88] lazyeval_0.2.3          ggfun_0.2.0             yaml_2.3.12            
#&gt;  [91] evaluate_1.0.5          codetools_0.2-20        gdtools_0.5.1          
#&gt;  [94] tibble_3.3.1            qvalue_2.44.0           ggplotify_0.1.3        
#&gt;  [97] cli_3.6.6               systemfonts_1.3.2       processx_3.9.0         
#&gt; [100] jquerylib_0.1.4         Rcpp_1.1.1-1.1          png_0.1-9              
#&gt; [103] parallel_4.6.0          blob_1.3.0              ggalluvial_0.12.6      
#&gt; [106] DOSE_4.6.0              viridisLite_0.4.3       tidytree_0.4.7         
#&gt; [109] ggiraph_0.9.6           enrichit_0.1.4          ggridges_0.5.7         
#&gt; [112] scales_1.4.0            purrr_1.2.2             crayon_1.5.3           
#&gt; [115] GetoptLong_1.1.1        rlang_1.2.0             KEGGREST_1.52.0</code></pre>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="enrichment.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="ml-analysis.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": true,
    "facebook": false,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": null,
    "text": null
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": null,
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
